### PR TITLE
Update prometheus to 0.4.1

### LINKED ISSUE #2939: Don't panic for incorrect metric values
For example, when a counter is going to decrease (due to some incorrect metric values), currently TiKV will panic. This is not a good behaviour, instead a warning log is preferred.

### PR DESCRIPTION
**Pull request by breeswish**
Since [prometheus 0.4.1](https://github.com/pingcap/rust-prometheus/pull/168), it won't panic if the given counter value is < 0 in debug builds.

Fix #2939

### CODE REVIEW

**Comment by breeswish** [comment]
@huachaohuang @BusyJay PTAL

**Comment by huachaohuang** [comment]
CI failed.

**Comment by breeswish** [comment]
Wired.. My local build is ok..

**Comment by breeswish** [comment]
Oh I got it! My local builds ignores threads_linux. How stupid I am.

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
