### PR TITLE
add memory usage metrics

### PR DESCRIPTION
**Pull request by UncP**

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
Please use prometheus::ProcessCollector.

**Comment by siddontang** [comment]
Prometheus library has already exported memory usage metrics. you can use it directly.

**Comment by zhangjinpeng1987** [comment]
Any update?

**Comment by UncP** [comment]
https://github.com/pingcap/rust-prometheus/pull/160

**Comment by UncP** [comment]
closing as memory metrics has existed.

**Pull request closed without merging**
