### PR TITLE
store: add propose log histogram metric

### PR DESCRIPTION
**Pull request by siddontang**
To see the log size distribution statistics. 

@BusyJay @hhkbp2 @overvenus

### CODE REVIEW

**Comment by hhkbp2** [comment]
Any estimate on the impact of performance?

**Comment by siddontang** [comment]
Of course, it will reduce the performance, but I think it is ok here. 
If you care the reduction, we can use a histogram cache and flush to prometheus metric in batch, but now we don't support it. Maybe you or @overvenus can try it later.

**Comment by hhkbp2** [comment]
@siddontang It's better to run some bench tests and get bench data, when adding new metrics for frequent operations. It seems that there is automatic bench test system would help.

**Comment by siddontang** [comment]
@overvenus did the benchmark before.
```
test histogram::bench_histogram_no_labels               ... bench:          20 ns/iter (+/- 6)
test histogram::bench_histogram_timer                   ... bench:          90 ns/iter (+/- 16)
test histogram::bench_histogram_with_label_values       ... bench:          86 ns/iter (+/- 1)
```

For the histogram with no labels, it is 20ns. So I think it is ok here. 

Of course, we can cache the histogram and flush in batch, but it is not easy as Counter and Gauge, and is it really necessary? /cc @overvenus

**Comment by hhkbp2** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @BusyJay @overvenus

**Pull request merged**
