### PR TITLE
[cherry-pick] Clear stale data using DeleteFilesInRanges

### PR DESCRIPTION
**Pull request by huachaohuang**

### CODE REVIEW

**Comment by huachaohuang** [comment]
/run-integration-tests tidb=release-1.0 pd=release-1.0 tidb-test=release-1.0

**Comment by zhangjinpeng1987** [comment]
LGTM

**Comment by huachaohuang** [comment]
/run-integration-tests tidb=release-1.0 pd=release-1.0 tidb-test=release-1.0

**Comment by UncP** [comment]
LGTM

**Pull request merged**
