### PR TITLE
raftstore: move coprocessor out

### PR DESCRIPTION
**Pull request by overvenus**
Let ourside to create coprocessor host.

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

PTAL @BusyJay

**Comment by BusyJay** [comment]
How about expose `config::Config` to `raftstore`? So you can still initialize `CoprocessorHost` in `Store`.

**Comment by overvenus** [comment]
I am fine with it.
What's your opinion? @siddontang

**Comment by siddontang** [comment]
> How about expose `config::Config` to `raftstore`

Seem the dependency is strange. 

If we don't want to create coprocessor host outside, I can accept add a `raftstore.coprocessor` config section like @overvenus previously did.

**Pull request closed without merging**
