### PR TITLE
raftstore/peer: revise leader lease time log

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi,

This PR revises the format of leader lease in log messages. It reverts the PR #1722. Because the leader lease is a monotonic time since startup time. It's confusing to output it in absolute time format. This PR changes the leader lease format from `"1970/01/01 00:17:01.272"` to `Timespec { sec: 51988, nsec: 392739700 }` for better description.

PTAL @javaforfun @BusyJay @siddontang

### CODE REVIEW

**Comment by siddontang** [comment]
em, I think it is hard to understand too...

**Comment by javaforfun** [comment]
LGTM

**Comment by hhkbp2** [comment]
@siddontang 
> em, I think it is hard to understand too...
Any better idea?

**Comment by siddontang** [comment]
No, I have no idea now. 

So LGTM

**Pull request merged**
