### PR TITLE
raft: fix wrong slice

### PR DESCRIPTION
**Pull request by BusyJay**
@ngaut @siddontang PTAL

### CODE REVIEW

**Comment by xiang90** [comment]
@BusyJay Is this also a problem in etcd/raft? cc me if you find any specious issues. for new test cases here, i will add tests to etcd/raft accordingly.

**Comment by BusyJay** [comment]
@xiang90 etcd/raft doesn't have the same issue. But the previous test cases don't cover [L315](https://github.com/coreos/etcd/blob/master/raft/log.go#L315).

**Comment by xiang90** [comment]
@BusyJay I will add the test case. Thanks!

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
@siddontang PTAL

**Pull request merged**
