### PR TITLE
tests/raftstore: fix down peers test

### PR DESCRIPTION
**Pull request by huachaohuang**
The test fails occasionally because the `down_secs` can be 0.

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
Why `down_secs` can be 0?

**Comment by BusyJay** [comment]
Then we should change the behaviour of mock pd, when receives a report for down peers, it should set the down time of these peer to a non-zero value.

**Comment by hhkbp2** [comment]
Any progress? This issue blocks #1473

**Comment by ngaut** [comment]
ping @huachaohuang

**Comment by huachaohuang** [comment]
I don't think we should change the behavior of mock pd for this test, it's weird.
The current patch should be enough to ensure the down time is reset after leader switch.
PTAL

**Comment by BusyJay** [comment]
I think it's weird too when down time is 0. Maybe we can change the downtime configuration to 1s instead of 0.5s.

**Pull request merged**
