### PR TITLE
expression: add builtin crc32

### PR DESCRIPTION
**Pull request by TennyZhuang**
## What have you changed? (mandatory)

* add `crc32` function in `builtin_math.rs`

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

pass `make expression`

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No

## Does this PR affect tidb-ansible update? (mandatory)

No

### CODE REVIEW

**Comment by breeswish** [comment]
Thanks for your contribution! LGTM

**Comment by TennyZhuang** [comment]
@breeswish It seems that there is not a proper category for `crc32` in #3275 , should I create a simple test fn named `test_crc32` and only test for `crc32`?

**Comment by breeswish** [comment]
@TennyZhuang Yes! Please go on. test_crc32 would be much like other test_xxx, only differs in that it tests for crc32 function. Also you may consider adding multiple tests like [this in TiDB](https://github.com/pingcap/tidb/pull/2347/files#diff-ef4dfa0fb8d0c9b85a6d4b377688142bR181). If you can add some tests of multi-byte characters it would be perfect!

**Comment by TennyZhuang** [comment]
@breeswish I add `test_crc32` now, and add a multi-byte character test.

**Pull request merged**
