### PR TITLE
coprocessor: add more observer

### PR DESCRIPTION
**Pull request by BusyJay**
So more functionality can be implemented without polluting raftstore codebase.

This pr also splits `RegionObserver` into three different parts, so hooks will never be called if no one is interested in it.

/cc #2309, @blacktear23 does it meet your need?

### CODE REVIEW

**Comment by siddontang** [comment]
@blacktear23 

I think you should implement your own Admin and Query observer to hook pre and post apply.

**Comment by blacktear23** [comment]
gotcha

**Comment by siddontang** [comment]
PTAL @overvenus

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
Ping @overvenus

**Pull request merged**
