### PR TITLE
Makefile: flamegraph friendly release

### PR DESCRIPTION
**Pull request by overvenus**
Disable some optimization to generate readable flamegraphs.

Before:

screenshot from 2018-07-19 17-56-52

After:

screenshot from 2018-07-19 17-56-25

### CODE REVIEW

**Comment by siddontang** [comment]
cool

have you tried passing `inline` flag for the stack collapse, https://github.com/brendangregg/FlameGraph/blob/master/stackcollapse-perf.pl#L104, maybe this can resolve the symbol too.

**Comment by breeswish** [comment]
How is the performance impact? Can we turn it on by default? Is it a good replacement of [using `--call-graph=dwarf`](https://github.com/pingcap/tidb-inspect-tools/pull/40) ?

**Comment by breeswish** [comment]
Issue number 3333  :)

**Comment by siddontang** [comment]
If perf can solve this problem by itself, I think we don't need to build another release for perf separately.

**Comment by overvenus** [comment]
Yes, I think dwarf is better.

**Pull request closed without merging**
