### PR TITLE
raftstore: add metrics APPLY_TASK_WAIT_TIME_HISTOGRAM.

### LINKED ISSUE #2492: raftstore: add a metric for apply task waiting time
Like REQUEST_WAIT_TIME_HISTOGRAM to check the raftstore channel wait time, we can also add a APPLY_TASK_WAIT_TIME_HISTOGRAM to see the time when we send the apply task and run it in the apply worker.

### PR DESCRIPTION
**Pull request by hicqu**
Fix #2492 .

### CODE REVIEW

**Comment by siddontang** [comment]
I think you must use two PR. 

Btw, I suggest referring the implementation of the threadpool context if you want to refactor worker, maybe:

1. Add a `on_tick` interface
2. First use try_recv, if no item, then fall back to recv_timeout, if the timeout happens, loop timeout again.

**Comment by BusyJay** [comment]
Is it really necessary to use LocalHistogram?

**Comment by hicqu** [comment]
@BusyJay does you mean all `ApplyRunner`s can concurrent update one `Histogram`, which is not very frequently？

**Comment by BusyJay** [comment]
There is only one ApplyRunner.

**Comment by siddontang** [comment]
@hicqu 

We may use multi-thread for apply worker later, but now we have only one. If we use multi-thread, we can use the thread-pool directly.

**Comment by siddontang** [comment]
any update? @hicqu

**Pull request closed without merging**
