### PR TITLE
Prepare 1.0.4

### PR DESCRIPTION
**Pull request by BusyJay**
Cherry pick several commits from master and prepare to bump 1.0.4

### CODE REVIEW

**Comment by disksing** [comment]
LGTM.

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
/run-integration-tests tidb=release-1.0 pd=release-1.0 tidb-test=release-1.0

**Comment by BusyJay** [comment]
CI fails due to the lack of #2532

**Pull request merged**
