### PR TITLE
*: add messages_per_tick config.

### PR DESCRIPTION
**Pull request by siddontang**
default 256 may be too small when we have thousands of regions.

@ngaut @BusyJay @disksing @zhangjinpeng1987

### CODE REVIEW

**Comment by ngaut** [comment]
Any bench results ?

**Comment by siddontang** [comment]
I will add a benchmark later.

**Comment by ngaut** [comment]
It works. 256 is too small.

**Comment by ngaut** [comment]
LGTM.
Please rebase master.

**Comment by siddontang** [comment]
PTAL @BusyJay @disksing @zhangjinpeng1987

**Comment by disksing** [comment]
LGTM

**Comment by zhangjinpeng1987** [comment]
LGTM

**Pull request merged**
