### PR TITLE
tests: make failpoints tests more stable

### PR DESCRIPTION
**Pull request by overvenus**
CC https://github.com/pingcap/tikv/pull/2545#issuecomment-353917300

### CODE REVIEW

**Comment by siddontang** [comment]
Can you explain that why do you add this?

**Comment by overvenus** [comment]
Failpoints tests share a global lock. A failed test may cause panic before unlocking, leaves the lock poisoned, remaining tests will never acquire it successfully.

**Comment by siddontang** [comment]
LGTM

PTAL @disksing

**Pull request merged**
