### PR TITLE
scanner with upper bound

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
scanner with upper bound.
ref https://github.com/pingcap/tikv/issues/1467
@BusyJay @siddontang PTAL

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
Any test to cover upper bound and no upper bound?

**Comment by zhangjinpeng1987** [comment]
Tests in `test_select.rs` has covered scan with upper bound and without upper bound.

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
CI failed @zhangjinpeng1987

**Pull request merged**
