### PR TITLE
correct typos

### PR DESCRIPTION
**Pull request by ShalokShalom**

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @ShalokShalom 

Please sign the CLA, LGTM

**Comment by ShalokShalom** [comment]
I have no idea
You can commit this yourself 
Its just a few typos corrected :)

**Comment by siddontang** [comment]
Hi @ShalokShalom 

We highly appreciate your contribution and would like to recognize you as our contributor once you sign the CLA by clicking the CLA button and accept the agreement. 

The CLA button is 
image

**Comment by ShalokShalom** [comment]
Done :slight_smile:

**Comment by ShalokShalom** [comment]
Done :slightly_smiling_face:

**Comment by siddontang** [comment]
PTAL @queenypingcap

**Comment by huachaohuang** [comment]
LGTM

**Comment by queenypingcap** [comment]
LGTM

**Pull request merged**
