### PR TITLE
Add test for reverse seek

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
This test simulate a case that `reverse_seek` will iterate write cf's tombstones repeatedly.
In the test, there are about 60k RocksDB tombstones in write cf and 255 keys in lock cf. The `reverse_seek` takes 327 seconds to return.
```
➜  [20.1] tikv git:(458e158) ✗ cargo test test_mvcc_reader_reverse_scan -- --nocapture
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/tikv-3aa30f01ae3213cf

running 1 test
test storage::mvcc::reader::tests::test_mvcc_reader_reverse_scan ... test storage::mvcc::reader::tests::test_mvcc_reader_reverse_scan has been running for over 60 seconds
reverse scan elapsed: Duration { secs: 327, nanos: 721437829 }
test storage::mvcc::reader::tests::test_mvcc_reader_reverse_scan ... ok
```

### CODE REVIEW

**Comment by breeswish** [comment]
Do we have solutions to migrate this problem?

**Comment by zhangjinpeng1987** [comment]
Currently for all type of reading, including point get, scan, reverse scan and check transaction constraint before write, we all use the common MvccReader to satisfy these demands. This lead to a result that the MvccReader is a common implementation for all case, it doesn't handle very well for some extraordinary cases. When we find a such case, the normal solution is to write a patch to MvccReader. I don't think this is a good way to solve the problem.

I think we can use different readers for different type of readings, and these readers share some real common methods. When we write or optimize such kind of reader, what we need to do is to consider the only use case, not all use cases, so it is easier to optimize and harder to miss some extraordinary cases.

**Comment by siddontang** [comment]
Do we need to merge this test?

**Comment by zhangjinpeng1987** [comment]
We will reopen this pr after the reverse scan problem has fixed.

**Pull request closed without merging**
