### PR TITLE
bin: rocksdb tuning

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
rocksdb tuning.

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
PTAL

**Comment by siddontang** [comment]
change these in default config template file too. in `/etc`

**Comment by zhangjinpeng1987** [comment]
PTAL @siddontang @ngaut @BusyJay @shenli

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Pull request merged**
