### PR TITLE
raftstore: remove schedule empty apply task

### PR DESCRIPTION
**Pull request by july2993**
we can see from the log, there's no need to schedule these task
```
root@july-VirtualBox:/usr/local/tidb-latest-linux-amd64# tail -f /tmp/kv2.log |grep "task async"
2018/01/21 09:13:48.536 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:48.857 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:48.859 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:48.860 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:48.861 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.647 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.648 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.959 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.961 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.970 mod.rs:147: [DEBUG] scheduling task async applys count 0
2018/01/21 09:13:49.970 mod.rs:147: [DEBUG] scheduling task async applys count 0
```

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
Thanks @july2993 

LGTM

**Pull request merged**
