### PR TITLE
*: update rocksdb

### PR DESCRIPTION
**Pull request by BusyJay**
Now rocksdb is always built and linked statically.

Note: this is a breaking changes for developers. If they used a customized rocksdb, it no longer work as expected anymore.

/cc @iamxy

### CODE REVIEW

**Comment by BusyJay** [comment]
close #2365 
/cc #2359, #2315, #2451

**Comment by siddontang** [comment]
CI failed

**Comment by iamxy** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

@BusyJay after this PR, we should clean up the development document.

**Pull request merged**
