### PR TITLE
*: add tag for logging and debugging

### PR DESCRIPTION
**Pull request by ngaut**
Currently, the log inside of raft module has no relationship with region. It's hard to find out which region that the raft belongs to. We need a simply way to handle this problem without change the implementation of raft.

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
LGTM

**Comment by ngaut** [comment]
@xiang90 Is it necessary to add the changes to etcd's raft implementation?

**Comment by siddontang** [comment]
I think it is not necessary for etcd, it has only one region.

**Pull request merged**
