### PR TITLE
store: reduce GC limit

### PR DESCRIPTION
**Pull request by siddontang**
Like etcd, https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L44, we use 5000, 100000 seems too long. 

@ngaut @BusyJay @hhkbp2

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM. Since we have many raft group, we may use a smaller size in the future.

**Comment by BusyJay** [comment]
5000 maybe too small when doing snapshot. See tikv/issues#424.

**Comment by siddontang** [comment]
Maybe a better way is that if doing snapshot, we can enlarge this value.

**Comment by siddontang** [comment]
I file an issue https://github.com/pingcap/tikv/issues/1337 and will close this PR. 
We should think a better way to handle it.

**Pull request closed without merging**
