### PR TITLE
copr: fix decimal

### PR DESCRIPTION
**Pull request by BusyJay**
@coocood @siddontang @disksing PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
should we add some invalid string test?

**Comment by BusyJay** [comment]
Added already, see `test_parse_decimal_fail`.

**Comment by siddontang** [comment]
LGTM

**Comment by coocood** [comment]
This bug was found by evaluating a comparison expression, we should add some test cases in `util/xeval`.

**Comment by coocood** [comment]
LGTM

**Pull request merged**
