### PR TITLE
store: only leaders can heartbeat pd after splitting

### PR DESCRIPTION
**Pull request by overvenus**
This PR prevents followers heartbeat pd adter splitting.

### CODE REVIEW

**Comment by disksing** [comment]
PTAL @nolouch

**Comment by siddontang** [comment]
Does any test cover this?

**Comment by overvenus** [comment]
A friendly ping.

**Comment by BusyJay** [comment]
I suggest to use term to filter out stale heartbeat. We can't guarantee the source peer is still leader when the heartbeat arrives pd.

**Comment by overvenus** [comment]
Do you mean add a `uint64 term` in the RegioHeartbeat message?

**Comment by BusyJay** [comment]
Yes.

**Comment by overvenus** [comment]
Interesting, it's actually a feature for performance.

**Pull request closed without merging**
