### PR TITLE
Cargo: disable prometheus process feature

### PR DESCRIPTION
**Pull request by overvenus**
We should enable `process` feature after pingcap/rust-prometheus#96 been merged.

PTAL @siddontang @BusyJay @iamxy

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
Will thread cpu collector still work after merging this pr?

**Comment by overvenus** [comment]
Yes, it will.

???? iPhone

? 2017?1?16??12:42?Jay <notifications@github.com<mailto:notifications@github.com>> ???


Will thread cpu collector still work after merging this pr?

-

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
