### PR TITLE
storage: move raw_get to thread pool.

### PR DESCRIPTION
**Pull request by disksing**
@zhangjinpeng1987 @siddontang

### CODE REVIEW

**Comment by ngaut** [comment]
Any performance bench results?

**Comment by zhangjinpeng1987** [comment]
LGTM

**Comment by siddontang** [comment]
Any test?

**Comment by disksing** [comment]
Hi @ngaut @siddontang , I've compared it with master branch. (1 tikv, prepare ~10GiB data using rawkv api)
The result:
a) in read-only scenario, QPS are almost the same, while CPU% of `raftsore` decreases from 90% to 50%.
b) in read-write(1:1) scenario, QPS increased about 25%-40%.

**Comment by siddontang** [comment]
Cool.

Please add unit test for Get.

**Comment by disksing** [comment]
@siddontang We already have some tests covered rawget in https://github.com/pingcap/tikv/blob/master/tests/storage/test_storage.rs

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
