### PR TITLE
store: open check quorum default.

### PR DESCRIPTION
**Pull request by siddontang**
@ngaut @BusyJay

### CODE REVIEW

**Comment by ngaut** [comment]
Any tests to make sure it works ?

**Comment by siddontang** [comment]
no, hard to simulate now, later @tiancaiamao can add it with some strategies.

**Comment by BusyJay** [comment]
Why open this option?

**Comment by tiancaiamao** [comment]
if leader doesn't receive from majority, it will make a appendlog request to verify it's still leader. This can accelerate detection of some problem by avoid waiting for election timeout @BusyJay 

as for tests, this PR has a dependency https://github.com/pingcap/tikv/pull/451 , while the later won't work before we fix CI https://github.com/pingcap/tikv/issues/427 @ngaut

**Comment by BusyJay** [comment]
> if leader doesn't receive from majority, it will make a appendlog request to verify it's still leader. 
I don't think so. It will just step down as follower in this case.
> ... by avoid waiting for election timeout 
Actually it checks quorum after election timeout.

**Comment by tiancaiamao** [comment]
you're right... I verify the code  just now...
I misunderstand or that can be a bonus

**Comment by siddontang** [comment]
Opening this is ok, if election timeout, the stale leader will try to check its whether it is still leader first, so we don't start the election again. 

Etcd opens this too. /cc @xiang90

**Comment by BusyJay** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Comment by xiang90** [comment]
We were not trying to make this a fancy algorithm. Leader just simply checks if receives ANY valid append responses or heartbeat responses from the majority. If not, then it steps down. If you feel this is too aggressive, you can make it step down after 2 election timeout. If you feel this is too conservative, you can make it steps down after 1/2 election timeout. If you want to be fancy, you can make this adaptive.

For etcd, we just want to make sure the leader does step down. Without enabling this, the old leader might never step down if it is partitioned with the other nodes.

**Comment by ngaut** [comment]
Thanks for explanation @xiang90

**Pull request merged**
