### PR TITLE
raftstore: suppress compact log

### PR DESCRIPTION
**Pull request by BusyJay**

### CODE REVIEW

**Comment by siddontang** [comment]
why not removing log in apply.rs?

**Comment by BusyJay** [comment]
Because I think it's appropriate and necessary to log all the admin action.

**Comment by siddontang** [comment]
Do we need to add a metric counter for the compacted logs?

**Comment by BusyJay** [comment]
I'm not sure. I think the log lag metrics reflect it in a way.

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @javaforfun

**Pull request merged**
