### PR TITLE
coprocessor/dag: fix bug caused by check meta in chunk

### PR DESCRIPTION
**Pull request by AndreMouche**
cherry-pick https://github.com/pingcap/tikv/pull/2476
@hicqu @BusyJay PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
CI failed @AndreMouche

**Comment by AndreMouche** [comment]
It's caused by `test_node_base_split_region_right_derive` and the related issue is https://github.com/pingcap/tikv/issues/2487 @siddontang

**Comment by hicqu** [comment]
LGTM.

**Pull request merged**
