### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by Richard-zhang**
Fixed some typos 
inproper => improper
zeroes => zeros
entris => entries
compareable => comparable

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @Richard-zhang 

Btw, I think `zeroes` is right, /cc @queenypingcap

**Comment by Richard-zhang** [comment]
@siddontang I will change zero back. Thanks. Zeroes and Zeros are both valid plural form.

**Comment by siddontang** [comment]
Thanks @Richard-zhang 

You can help us change all zeros to zeroes or vice versa.  

/cc @queenypingcap what do you think is better?

**Comment by siddontang** [comment]
LGTM

PTAL @queenypingcap @BusyJay

**Comment by queenypingcap** [comment]
LGTM.

**Pull request merged**
