### PR TITLE
makefile: disable clippy by default

### PR DESCRIPTION
**Pull request by BusyJay**
@ngaut @siddontang @disksing @zhangjinpeng1987 PTAL

### CODE REVIEW

**Comment by BusyJay** [comment]
This pr will resolve #523 when just using `make`.

**Comment by siddontang** [comment]
so we will use `make dev` now?

**Comment by BusyJay** [comment]
Yes.

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
