### PR TITLE
kvrpc: do not use proto's has_xx.

### PR DESCRIPTION
**Pull request by disksing**
@shenli @siddontang @zhangjinpeng1987

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by shenli** [comment]
LGTM

**Comment by siddontang** [comment]
But gogo doesn't affect rust

**Comment by siddontang** [comment]
is it necessary?

**Comment by disksing** [comment]
@siddontang Yes. Since we add a 'nullable=false' flag, has() will always return true even if go client do not set it.

**Comment by siddontang** [comment]
ok

**Comment by ngaut** [comment]
Are there some other cases ?

**Comment by disksing** [comment]
@ngaut I've checked all usages. But we should take care if we want to add more 'nullable' in the future.

**Comment by ngaut** [comment]
Can we build a script that search nullable flag and source of tikv to make sure we don't make any mistake ?

**Comment by BusyJay** [comment]
It seems very easy to make mistake when dealing with the `nullable=false` flag.

**Comment by siddontang** [comment]
yes, `nullable=false` means the field can't be none, we can't use `has` for this field, I think the best way is rust protocbuf can parse this and don't generate `has` function.

**Comment by siddontang** [comment]
Or we can check the generated rs file and move has function in our building script too.

**Comment by ngaut** [comment]
Can we simply remove nullable=false ?

**Comment by disksing** [comment]
@ngaut I've cross compared and no other case is found.

**Comment by siddontang** [comment]
no, we must use `nullable = false` now for optimization in gogo.

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
