### PR TITLE
Add metrics and log for txn

### PR DESCRIPTION
**Pull request by wentaoxu**
as title says

### CODE REVIEW

**Comment by wentaoxu** [comment]
PTAL @zhangjingpeng1987 @AndreMouche

**Comment by huachaohuang** [comment]
Is it really necessary to rename "snapshot" to "txn_snapshot"?
I think there is no other "snapshot" concept in the "txn" module.

**Comment by wentaoxu** [comment]
@huachaohuang yes, but there is in `raftstore`

**Comment by siddontang** [comment]
I have the same question here, for the metrics, we already have the sub-namespace so we can distinguish txn and raftstore. 

I guess you here just want to let the Grafana show clearly, maybe you should update Grafana only.

**Comment by siddontang** [comment]
any update?

**Comment by wentaoxu** [comment]
@siddontang agree with you, I will take a look at granfana.

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
