### PR TITLE
circleci: Specify tarpaulin version

### PR DESCRIPTION
**Pull request by Hoverbear**
Specifies the version of Tarpaulin to triage the CI breaking.

See https://circleci.com/gh/pingcap/tikv/11095

You can see that in the last week `cargo-tarpaulin` (https://github.com/xd009642/tarpaulin/releases) updated a few times. This has resulted in a recent build breakage on our particular version of nightly. This might be able to be refined in #3066 .

## What are the type of the changes? (mandatory)

- Bug fix (non-breaking change which fixes an issue)

## How has this PR been tested? (mandatory)

By the CI (which had a build error!)

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

I do not expect it to.

## Does this PR affect tidb-ansible update? (mandatory)

It should not.

### CODE REVIEW

**Comment by breeswish** [comment]
build failed 🤣

**Comment by Hoverbear** [comment]
Yes I forgot a thin. :disappointed:

**Comment by siddontang** [comment]
CI failed

**Comment by Hoverbear** [comment]
@codeworm96 did you have any problems around versions with Tarpaulin?

**Comment by codeworm96** [comment]
0.5.6 is too old. TiKV uses the `nested import groups` syntax, which requires a tarpaulin version `>= 0.6.0`

**Comment by codeworm96** [comment]
According to https://users.rust-lang.org/t/cargo-install-and-lock-file/4203, install from git could be a workaround for that.

I tried ` RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly-2018-04-06 install cargo-tarpaulin --git https://github.com/xd009642/tarpaulin --tag 0.6.0 --force`. It works.

**Comment by Hoverbear** [comment]
@codeworm96 :+1: That is a good work around until #3208 lands.

**Comment by breeswish** [comment]
Will this still be a problem once https://github.com/pingcap/tikv/pull/3208 is landed?

**Comment by siddontang** [comment]
PTAL @overvenus @breeswish

**Comment by breeswish** [comment]
@siddontang LGTM, however I'm not sure whether or not we will still face this issue after merging #3208 .

**Comment by breeswish** [comment]
I used the rustc version specified in #3208, and seems that it works fine without this PR's patch.

**Comment by codeworm96** [comment]
@breeswish The root cause of the issue is the release of `regex 1.0.1`, which depends on the stabilization of x86/x86_64 SIMD (https://github.com/rust-lang/rust/pull/49664) and thus requires a newer rustc version.

PS: In my opinion, since TiKV is pinning rustc version, it is reasonable to pin these tools' versions as well, in case that they may release a new version that depends on newer rustc.

**Comment by breeswish** [comment]
@codeworm96 Ok, you are right. I just came out a new idea. Is cargo install really needed? Can we just binary install it, so that we are really pinning to a specific version, which is not affected even if we upgrade rustc?

**Comment by breeswish** [comment]
As a hot fix for master, I'm going to merge this PR. However I think there can be more to do, for example, using a binary instead so that we won't suffer from rustc any more. This can be improved by future PRs.

**Pull request merged**
