### PR TITLE
tests: larger query leader timeout

### LINKED ISSUE #3079: raftstore_cases::test_split_region::test_server_apply_new_version_snapshot' panicked
```
thread 'raftstore_cases::test_split_region::test_server_apply_new_version_snapshot' panicked at 'called `Result::unwrap()` on an `Err` value: Other(StringError("[tests/raftstore/cluster.rs:262]: can\'t get leader of region 1000"))', libcore/result.rs:945:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:72
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:782
  10: <integrations::raftstore::cluster::Cluster<T>>::request
             at tests/raftstore/cluster.rs:564
  11: <integrations::raftstore::cluster::Cluster<T>>::get_impl
             at tests/raftstore/cluster.rs:628
  12: <integrations::raftstore::cluster::Cluster<T>>::get
             at tests/raftstore/cluster.rs:616
  13: integrations::raftstore_cases::test_split_region::test_apply_new_version_snapshot
             at tests/raftstore_cases/test_split_region.rs:471
  14: integrations::raftstore_cases::test_split_region::test_server_apply_new_version_snapshot
             at tests/raftstore_cases/test_split_region.rs:492
  15: integrations::__test::TESTS::{{closure}}
             at tests/raftstore_cases/test_split_region.rs:490
  16: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  17: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1453
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:635
  18: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
```

### PR DESCRIPTION
**Pull request by overvenus**
10ms is too short, it may never get responses even if a leader is elected.  

Close #3079 
Close #3089

### CODE REVIEW

**Comment by BusyJay** [comment]
But it will retry after timeout, so is it OK to take 10ms * 500 finish a campaign when election timeout is 250ms? If you change it to 100ms, does it mean it will take at least 50s to report error when there is something wrong?

**Comment by overvenus** [comment]
Besides campaigns, query requests are queued in raftstore channel, so if there are many time consuming requests or slow disk, 10ms * 500(5s) may not enough.

**Comment by BusyJay** [comment]
> many time consuming requests or slow disk

Any logs or metrics?

**Comment by overvenus** [comment]
#3079 and #3080 have backtraces, but test's log is gone, unfortunately. You can see #3073, `jenkins-ci-tikv/unit-test` failed frequently.

**Comment by BusyJay** [comment]
It fails doesn't mean 5s is too short. It can due to inappropriate configured isolation or anything possible. In 5s it can campaign 10 times. There is probably something wrong when it fails to campaign after trying so many times.

**Comment by overvenus** [comment]
A friendly ping.

**Pull request closed without merging**
