### PR TITLE
no need to overwrite data in prewrite

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
@disksing @siddontang PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
any test?

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tikv/blob/master/src/storage/mvcc/txn.rs#L327 has cover this case.

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
CI failed @zhangjinpeng1987

**Pull request merged**
