### PR TITLE
raftstore: beautify task log

### LINKED ISSUE #3334: we need a pretty log format
2018/07/19 19:06:42.661 WARN mod.rs:97: handle task CheckAndCompact { cf_names: ["default", "write"], ranges: [[122], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 7, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 11, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 15, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 19, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 23, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 27, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 31, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 35, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 39, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 43, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 47, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 51, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 55, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 67, 105, 4, 3, 128, 0, 0, 255, 0, 2, 255, 229, 96, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 96, 47, 4, 3, 128, 0, 0, 255, 0, 0, 151, 109, 49, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 128, 154, 180, 3, 128, 0, 0, 255, 0, 0, 128, 3, 214, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 167, 118, 94, 3, 128, 0, 0, 255, 0, 1, 32, 54, 181, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 199, 49, 46, 3, 128, 0, 0, 255, 0, 3, 121, 109, 206, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 214, 58, 122, 3, 128, 0, 0, 255, 0, 0, 245, 97, 105, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 243, 81, 184, 3, 128, 0, 0, 255, 0, 1, 46, 183, 249, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 247, 65, 165, 3, 128, 0, 0, 255, 0, 1, 24, 41, 162, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 247, 134, 92, 3, 128, 0, 0, 255, 0, 0, 34, 252, 130, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 247, 220, 168, 3, 128, 0, 0, 255, 0, 1, 226, 47, 236, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 248, 9, 89, 3, 128, 0, 0, 255, 0, 2, 7, 70, 163, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 248, 78, 184, 3, 128, 0, 0, 255, 0, 1, 154, 46, 220, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 248, 148, 212, 3, 128, 0, 0, 255, 0, 1, 87, 10, 112, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 248, 184, 34, 3, 128, 0, 0, 255, 0, 0, 26, 16, 58, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 249, 12, 62, 3, 128, 0, 0, 255, 0, 2, 96, 128, 165, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 249, 56, 31, 3, 128, 0, 0, 255, 0, 0, 153, 160, 108, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 249, 124, 65, 3, 128, 0, 0, 255, 0, 1, 145, 251, 100, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 249, 188, 231, 3, 128, 0, 0, 255, 0, 1, 10, 184, 101, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 249, 222, 178, 3, 128, 0, 0, 255, 0, 0, 109, 107, 153, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 250, 30, 125, 3, 128, 0, 0, 255, 0, 3, 59, 116, 202, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 250, 64, 103, 3, 128, 0, 0, 255, 0, 1, 202, 127, 227, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 250, 114, 192, 3, 128, 0, 0, 255, 0, 0, 79, 20, 35, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 250, 198, 176, 3, 128, 0, 0, 255, 0, 2, 45, 146, 8, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 250, 242, 237, 3, 128, 0, 0, 255, 0, 0, 22, 60, 34, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 251, 54, 149, 3, 128, 0, 0, 255, 0, 1, 3, 54, 184, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 251, 119, 164, 3, 128, 0, 0, 255, 0, 0, 78, 46, 197, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 251, 153, 125, 3, 128, 0, 0, 255, 0, 0, 114, 76, 75, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 251, 218, 155, 3, 128, 0, 0, 255, 0, 1, 22, 32, 115, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 251, 252, 227, 3, 128, 0, 0, 255, 0, 2, 179, 107, 111, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 252, 50, 18, 3, 128, 0, 0, 255, 0, 0, 6, 255, 160, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 252, 114, 248, 3, 128, 0, 0, 255, 0, 3, 178, 176, 116, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 252, 149, 71, 3, 128, 0, 0, 255, 0, 1, 94, 115, 243, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 252, 201, 96, 3, 128, 0, 0, 255, 0, 1, 177, 64, 7, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 253, 26, 44, 3, 128, 0, 0, 255, 0, 0, 18, 41, 12, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 253, 89, 191, 3, 128, 0, 0, 255, 0, 0, 121, 84, 105, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 253, 123, 101, 3, 128, 0, 0, 255, 0, 0, 63, 51, 22, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 253, 172, 181, 3, 128, 0, 0, 255, 0, 1, 12, 84, 197, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 253, 246, 215, 3, 128, 0, 0, 255, 0, 0, 64, 158, 175, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 254, 67, 75, 3, 128, 0, 0, 255, 0, 3, 245, 100, 196, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 254, 106, 142, 3, 128, 0, 0, 255, 0, 0, 22, 141, 166, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 254, 184, 146, 3, 128, 0, 0, 255, 0, 3, 18, 20, 148, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 254, 225, 248, 3, 128, 0, 0, 255, 0, 2, 156, 192, 253, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 255, 30, 193, 3, 128, 0, 0, 255, 0, 0, 55, 124, 9, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 255, 113, 21, 3, 128, 0, 0, 255, 0, 3, 197, 108, 65, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 255, 154, 175, 3, 128, 0, 0, 255, 0, 0, 125, 245, 104, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 255, 216, 223, 3, 128, 0, 0, 255, 0, 1, 141, 91, 69, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 0, 23, 80, 3, 128, 0, 0, 255, 0, 1, 233, 138, 185, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 0, 56, 23, 3, 128, 0, 0, 255, 0, 0, 122, 116, 0, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 0, 134, 5, 3, 128, 0, 0, 255, 0, 3, 201, 15, 167, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 0, 174, 136, 3, 128, 0, 0, 255, 0, 0, 168, 87, 201, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 0, 236, 18, 3, 128, 0, 0, 255, 0, 0, 18, 233, 220, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 1, 43, 230, 3, 128, 0, 0, 255, 0, 0, 109, 123, 173, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 1, 75, 209, 3, 128, 0, 0, 255, 0, 0, 77, 44, 177, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 1, 136, 95, 3, 128, 0, 0, 255, 0, 5, 208, 30, 146, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 1, 167, 223, 3, 128, 0, 0, 255, 0, 1, 10, 254, 38, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 1, 214, 126, 3, 128, 0, 0, 255, 0, 0, 29, 86, 17, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 2, 22, 7, 3, 128, 0, 0, 255, 0, 2, 70, 166, 8, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 2, 55, 168, 3, 128, 0, 0, 255, 0, 3, 206, 109, 216, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 2, 105, 48, 3, 128, 0, 0, 255, 0, 2, 101, 80, 217, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 14, 207, 2, 3, 128, 0, 0, 255, 0, 0, 112, 222, 60, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 41, 205, 47, 3, 128, 0, 0, 255, 0, 0, 234, 179, 133, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 56, 247, 250, 3, 128, 0, 0, 255, 0, 0, 194, 45, 20, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 90, 171, 94, 3, 128, 0, 0, 255, 0, 2, 185, 54, 113, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 110, 130, 34, 3, 128, 0, 0, 255, 0, 1, 212, 17, 64, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 146, 212, 73, 3, 128, 0, 0, 255, 0, 0, 37, 122, 60, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 199, 177, 236, 3, 128, 0, 0, 255, 0, 5, 131, 213, 88, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 3, 253, 180, 182, 3, 128, 0, 0, 255, 0, 1, 94, 100, 57, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 1, 116, 9, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 5, 144, 179, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 11, 33, 101, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 16, 178, 23, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 22, 66, 201, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 27, 211, 123, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 33, 100, 45, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 38, 244, 223, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 44, 133, 145, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 50, 22, 67, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 55, 166, 245, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 61, 55, 167, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 66, 200, 89, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 72, 89, 11, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 77, 233, 189, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 83, 122, 111, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 89, 11, 33, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 94, 155, 211, 0, 0, 0, 0, 0, 250], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 114, 128, 0, 0, 0, 0, 255, 100, 44, 133, 0, 0, 0, 0, 0, 250]], tombstones_num_threshold: 10000, tombstones_percent_threshold: 30 } [takes 5.888s]

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
beautify task log

## What are the type of the changes? (mandatory)
Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
manual test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)
No

## Does this PR affect tidb-ansible update? (mandatory)
No

## Add a few positive/negative examples (optional)
before: 
mod.rs:97: handle task CheckAndCompact { cf_names: ["default", "write"], ranges: [[122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 7, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 11, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 15, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 19, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 23, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 27, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 31, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 35, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 39, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 43, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 47, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 51, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 55, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 0, 0, 0, 0, 0, 0, 0, 248], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 67, 105, 4, 3, 128, 0, 0, 255, 0, 2, 255, 229, 96, 0, 0, 0, 252], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 59, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 3, 128, 0, 0, 0, 255, 2, 96, 47, 4, 3, 128, 0, 0, 255, 0, 0, 151, 109, 49, 0, 0, 0, 252],......

after:
mod.rs:97: handle task CheckAndCompact { cf_names: ["default", "write"], ranges: (Some("zt\\200\\000\\000\\000\\000\\000\\000\\377\\007\\000\\000\\000\\000\\000\\000\\000\\370"), Some("zt\\200\\000\\000\\000\\000\\000\\000\\377;_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\003\\200\\000\\000\\000\\377\\002`/\\004\\003\\200\\000\\000\\377\\000\\000\\227m1\\000\\000\\000\\374")) ......

Fixes #3334

### CODE REVIEW

**Comment by siddontang** [comment]
> Some([[122], [122, 116, 128, 0, 0, 0, 0, 0, 0, 255, 7, 0, 0, 0, 0, 0, 0, 0, 248])

still ugly, can you escape the key?

**Comment by breeswish** [comment]
You can use `util::escape`.

**Comment by breeswish** [comment]
I guess clippy will suggest you to write `.map(escape)`. Also it would be better if it is not double quoted (i.e. `\` instead of `\\`). Rest LGTM.

**Comment by Connor1996** [comment]
@breeswish fix the double escaped. And `.map(escape)` cannot pass the compile since mismatch signature of `&&vec<u8>`with`&[u8]`

**Comment by breeswish** [comment]
LGTM

**Comment by breeswish** [comment]
How did you solve the double escape issue? I didn't see new commits.

**Comment by Connor1996** [comment]
@breeswish The code is just right. I used rust playground to do the test, and the former output is produced by `assert_eq! `which escape the escaped string, but the output of `println!("{}")` is correct which used in tikv code.

**Pull request merged**
