### PR TITLE
coprocessor/xeval: add abs int function impl

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi,

This PR add the implementation of math function `abs_int` to expression evaluator.

PTAL @XuHuaiyu @AndreMouche @lishihai9017 @andelf

### CODE REVIEW

**Comment by hhkbp2** [comment]
Related to https://github.com/pingcap/tikv/pull/2024

**Comment by AndreMouche** [comment]
@lishihai9017 @andelf @XuHuaiyu PTAL

**Comment by hhkbp2** [comment]
PTAL @XuHuaiyu @lishihai9017 @andelf

**Comment by XuHuaiyu** [comment]
LGTM

**Pull request merged**
