### PR TITLE
merge master to 2.0 rc4

### PR DESCRIPTION
**Pull request by siddontang**
@BusyJay @zhangjinpeng1987

### CODE REVIEW

**Comment by BusyJay** [comment]
I think you should update master first and then merge master to release-2.0.

**Comment by zhangjinpeng1987** [comment]
LGTM

**Comment by siddontang** [comment]
@BusyJay I have already updated master and then merge.

**Comment by BusyJay** [comment]
I mean you need to bump rc4 on master first.

**Pull request merged**
