### PR TITLE
storage: a better place for the fail point async_snapshot_finish

### PR DESCRIPTION
**Pull request by overvenus**
This PR moves `async_snapshot_finish` from the raftkv to the storage, because the original place will be call in the raftstore, so the fp will block the raftstore, that causes leader transfer failure and the test be blocked forever.

### CODE REVIEW

**Comment by siddontang** [comment]
Cool catch!!!

**Comment by overvenus** [comment]
PTAL @BusyJay @siddontang

**Comment by BusyJay** [comment]
@AndreMouche PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by disksing** [comment]
LGTM

**Pull request merged**
