### PR TITLE
[DNM] server: add a worker for receiving snapshot file

### PR DESCRIPTION
**Pull request by tiancaiamao**

### CODE REVIEW

**Comment by siddontang** [comment]
Seem no useless. 
Please make sure that your PR can do something and can let other know what you want to do.

**Comment by tiancaiamao** [comment]
later we'll send snapshot via file, currently, mio doesn't support non-block file io.
we can't block the event loop, so we need a background worker to do the file writing related work, that's what this PR for.

**Comment by siddontang** [comment]
Still confused, why don't you add this directly when you implement snapshot file transport? 
Btw, you have not implemented the base feature, why do you consider optimization now? appending data to a file is fast (If not fast, I think we should not use rocksdb too), does it really become a big performance problem here?

**Comment by tiancaiamao** [comment]
will be include in https://github.com/pingcap/tikv/pull/648

**Pull request closed without merging**
