### PR TITLE
util: send metrics in a background thread

### PR DESCRIPTION
**Pull request by overvenus**
Performance of the metrics is improved by 27%.

Benchmark:

```sh
$ cargo bench
test tests::bench_single_thread_new_buffer_udp   ... bench:         160 ns/iter (+/- 40)
test tests::bench_single_thread_old_buffer_udp   ... bench:         218 ns/iter (+/- 4)

# 3 threads send 15000 metrics concurrently.
$ cargo bench
test tests::bench_multi_thread_new_buffer_udp    ... bench:   4,737,403 ns/iter (+/- 266,298)
test tests::bench_multi_thread_old_buffer_udp    ... bench:   6,540,073 ns/iter (+/- 1,081,465)
```

### CODE REVIEW

**Comment by siddontang** [comment]
Hi @overvenus 

I think if you want to support async metric, maybe scheduling the metric directly to worker, letting the worker cache the metric and then sending it may be easy. 

Maybe we can bench this implementation too.

**Comment by overvenus** [comment]
@siddontang Scheduling every metric to worker is slower.

Benchmark:

```sh
$ cargo bench bench_single_thread
     Running target/release/bench_metric-b6de8d742c9d8b0f

running 4 tests
test tests::bench_single_thread_async_udp    ... bench:         383 ns/iter (+/- 149)
test tests::bench_single_thread_block_udp    ... bench:       5,540 ns/iter (+/- 154)
test tests::bench_single_thread_buffer_udp   ... bench:         219 ns/iter (+/- 3)
test tests::bench_single_thread_nonblock_udp ... bench:       5,523 ns/iter (+/- 231)

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured
```

[AsyncMetric gist](https://gist.github.com/overvenus/31b3adba8d60fbc81325a958a0e9fc9d)

**Comment by siddontang** [comment]
Cool, LGTM

**Comment by siddontang** [comment]
PTAL @ngaut @BusyJay

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
