### PR TITLE
tunning write cf

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
write's cf don't need point get, so we remove bloom filter; the amount of data of write cf is according to default cf, so we adjust write cf's block-cache-size according to default cf's block-cache-size(reduce memory usage); write is not heavy for this cf, so the default value of level0_slowdown_writes_trigger&&level0_stop_writes_trigger is enough.

### CODE REVIEW

**Comment by siddontang** [comment]
how much performance increases?

**Comment by zhangjinpeng1987** [comment]
The key point of this pr is to reduce the memory usage of tikv as long as drop some useless config for write cf.

**Comment by siddontang** [comment]
LGTM

**Comment by disksing** [comment]
LGTM

**Pull request merged**
