### PR TITLE
*: upgrade mio

### PR DESCRIPTION
**Pull request by BusyJay**
So latest rustc can compile TiKV successfully.

@siddontang @zhangjinpeng1987 @disksing PTAL

### CODE REVIEW

**Comment by BusyJay** [comment]
Please note that, this pr upgrades mio to 0.5.1 rather than 0.6, latter will introduce many incompatible changes. So let's upgrade it to 0.6 after we refactor server layer with grpc and other related component with tokio.

**Comment by siddontang** [comment]
Can we update the CI rust version to support latest rust and clippy?

**Comment by BusyJay** [comment]
Sure, maybe another pr.

**Comment by zhangjinpeng1987** [comment]
LGTM

**Comment by siddontang** [comment]
@BusyJay 

Please fix the conflict.

**Pull request merged**
