### PR TITLE
Wrap "unknown lints" into cfg_attr calls

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
## What have you changed? (mandatory)

I wrapped all clippy lints (I saw) into `cfg_attr`.

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

Manually.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

#3248

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
cc @Hoverbear

**Comment by siddontang** [comment]
LGTM

Thank you @GuillaumeGomez

**Comment by breeswish** [comment]
Thanks a lot! Seems that not all unknown_lints are wrapped [so the build will fail](https://circleci.com/gh/pingcap/tikv/11461?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link). You can run `make dev` and the compiler will tell you the remaining "unknown lints". 

Also there is a allow(unknown_lints) in bench-tikv.rs which you might want to drop as well.

**Comment by GuillaumeGomez** [comment]
I saw them for the "bench files" but didn't replace them. However I thought I found all them by just running `cargo build`. I'll replace the missing ones as well.

**Comment by siddontang** [comment]
PTAL @breeswish

**Comment by breeswish** [comment]
Good job! LGTM

**Comment by GuillaumeGomez** [comment]
Now as a second step I'll make the changes in the benches as well, like that the issue will be completely solved.

**Pull request merged**
