### PR TITLE
*: port Etcd randomized election timeout.

### PR DESCRIPTION
**Pull request by siddontang**
@ngaut @BusyJay

### CODE REVIEW

**Comment by BusyJay** [comment]
LGTM

**Comment by ngaut** [comment]
Any reference URL ?

**Comment by siddontang** [comment]
No need, just from newest code. 

https://github.com/coreos/etcd/blob/master/raft/raft.go#L938

**Comment by tiancaiamao** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
