### PR TITLE
raft: add panic handling for term() due to iob

### PR DESCRIPTION
**Pull request by hhkbp2**
For issue #961

### CODE REVIEW

**Comment by siddontang** [comment]
miss test?

**Comment by hhkbp2** [comment]
@siddontang 
The test case in TiKV is 

https://github.com/pingcap/tikv/blob/master/src/raftstore/store/peer_storage.rs#L824

which is modified specially for peer storage. It checks the index range before returning error unavailable:

https://github.com/pingcap/tikv/blob/master/src/raftstore/store/peer_storage.rs#L264

and the error it returns is `Err(Store(Other(StringError("entries\' high {} is out of bound lastindex {}"))))`. This returned error type is not the same with `MemStorage` in this PR. So this test case for checking the special error is omitted.

**Comment by siddontang** [comment]
We don't use `PeerStorage` in raft lib test, we use a `MemStorage`, is it not ok too?

**Comment by ngaut** [comment]
LGTM

**Comment by hhkbp2** [comment]
@siddontang 
There is no tests for the `MemStorage` in TiKV. As we could see in the source code, someone ported the test cases for `MemoryStorage` in etcd raft to test cases for `PeerStorage` in TiKV. It make more sense to test the production code rather than the `MemStorage` which used only for test, even though we could duplicate these test cases for both. So this PR just follows this convention.

**Comment by siddontang** [comment]
> There is no tests for the MemStorage in TiKV

We use `MemStorage` for raft library test, we will port the test here too.

**Comment by hhkbp2** [comment]
PTAL @siddontang @BusyJay

**Comment by siddontang** [comment]
Can we send PR to etcd for the added tests?

**Comment by hhkbp2** [comment]
@siddontang The raft impl of etcd already has these test cases.

**Comment by siddontang** [comment]
Got it. LGTM

**Pull request merged**
