### PR TITLE
mvcc/reader: ignore Lock when lock's type is Lock

### PR DESCRIPTION
**Pull request by AndreMouche**
When we adding an index, the row will be locked with 'lock' type, which means it's not allowed to write.

But the value is not changed. We can continue to read the row without the need to return an lock error when we meet the lock.
@disksing @zhangjinpeng1987 @coocood PTAL

### CODE REVIEW

**Comment by coocood** [comment]
@AndreMouche 
I think we should not modify the read ts.
It should just ignore the lock and continue to find the version <= read ts

**Comment by disksing** [comment]
LGTM.

**Comment by zhangjinpeng1987** [comment]
fn check_lock(&mut self, key: &Key, mut ts: u64) -> Result<Option<u64>> {
       if let Some(lock) = self.load_lock(key)? {
           if lock.ts <= ts {
               if ts == u64::MAX && key.raw()? == lock.primary {
                   // when ts==u64::MAX(which means to get latest committed version for
                   // primary key),and current key is the primary key, returns the latest
                   // commit version’s value
                   ts = lock.ts - 1;
               } else if lock.lock_type != LockType::Lock {
                   // There is a pending lock. Client should wait or clean it.
                   return Err(Error::KeyIsLocked {
                       key: key.raw()?,
                       primary: lock.primary,
                       ts: lock.ts,
                       ttl: lock.ttl,
                   });
               }
           }
       }
       Ok(Some(ts))
   }

**Comment by coocood** [comment]
LGTM

**Comment by disksing** [comment]
LGTM.

**Comment by siddontang** [comment]
Please add a description for it.

**Comment by zhangjinpeng1987** [comment]
LGTM

**Pull request merged**
