### PR TITLE
[WIP] Reference count region snapshots

### PR DESCRIPTION
**Pull request by breeswish**
- [x] Algorithm initial implementation
- [x] Test algorithms
- [x] Integrate into the store
- [ ] Integration Test

### CODE REVIEW

**Comment by siddontang** [comment]
IMO, I don't like this solution, it is complex and hard to guarantee correctness in the concurrency suitation. And we also need to re-consider it after introducing local-read thread.

I have some questions:

1. Do we really need a 10m for the timeout? Can we reduce the limit? IMO, 1m or 2m for scanning a region is long. If longer, there must be something wrong.
2. Do we gather the statistic that how is frequent the coprocessor holding the region snapshot when the region is been deleting? If not frequent, I think we don't need this feature.
3. After we use DeleteFilesInRange to delete the region, do we notify it to PD immediately?
4. What is the really problem for the PD scheduling?

**Comment by breeswish** [comment]
@zhangjinpeng1987 

@siddontang also suggests an interesting idea. We can just use timestamps to log the last reference time for each region. We can immediately clean up regions that referenced longer than 10 minutes. This can be a more simple alternatives. However we need to check how often it is that a region is going to be moved in 10 minutes since last snapshot.

**Comment by zhangjinpeng1987** [comment]
I think you can remove `pending_delete_ranges` in this pr.

**Comment by breeswish** [comment]
This PR will be replaced by a simpler one. So it is closing for now.

**Pull request closed without merging**
