### PR TITLE
upgrade to rocksdb 5.6.1

### PR DESCRIPTION
**Pull request by choleraehyq**
@siddontang @zhangjinpeng1987 @follitude PTAL

Signed-off-by: Cholerae Hu <huyingqian@pingcap.com>

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
It's not just about ci. Should update rust-rocksdb too.

**Comment by choleraehyq** [comment]
rust-rocksdb updated.

**Comment by BusyJay** [comment]
travis-build/Makefile should be updated too.

**Comment by choleraehyq** [comment]
Updated.

**Pull request merged**
