### PR TITLE
Remove useless unknown_lints

### LINKED ISSUE #3248: Remove `allow(unknown_lints)`
There are built-in lints and [rust clippy](https://github.com/rust-lang-nursery/rust-clippy) lints. When we `allow` a clippy lint rule without specifying `feature = cargo-clippy`, it will be an unknown lint when clippy is not enabled.

Currently we enabled "allow(unknown_lints)" so that they won't bother us. However it is not a good idea since we can't know the removal of clippy lints as well. So a better solution is to explicitly allow these lint rules only when `feature = cargo-clippy`.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
## What have you changed? (mandatory)

Remove useless `#[allow(unknown_lints)]` (follow up of #3279).

## What are the type of the changes? (mandatory)

- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

I built the code.

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

No.

## Does this PR affect tidb-ansible update? (mandatory)

No.

## Refer to a related PR or issue link (optional)

It should fix #3248.

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by breeswish** [comment]
Thanks a lot! LGTM

**Comment by breeswish** [comment]
Why is this deny rule only added to tikv-bench, not globally effective?

**Comment by GuillaumeGomez** [comment]
I didn't know if you wanted to have a global `#![deny(warnings)]`. I tested it on benches and it worked but not sure you'd want it for all the project.

**Comment by BusyJay** [comment]
I don't think it's a good idea. Warnings usually have the least priority to be fixed during a development. Denying it explicitly can waste time when we just want to do some quick tweak.

And warnings are denied in CI already, which should be good enough.

**Comment by GuillaumeGomez** [comment]
Should I remove the `#![deny(warnings)]` for the benches then?

**Comment by breeswish** [comment]
@GuillaumeGomez Oh, yes. I think @BusyJay 's concern is reasonable.

**Comment by breeswish** [comment]
LGTM

**Comment by breeswish** [comment]
I would like to wait https://github.com/pingcap/tikv/pull/3294 to be merged first, since our CI is actually not checking clippy currently.

**Comment by Hoverbear** [comment]
@breeswish It has been merged now.

**Pull request merged**
