### PR TITLE
clippy: remove todo about clippy#1586

### PR DESCRIPTION
**Pull request by choleraehyq**
Issue https://github.com/Manishearth/rust-clippy/issues/1586 has already been fixed: https://github.com/Manishearth/rust-clippy/pull/1804

Signed-off-by: Cholerae Hu <huyingqian@pingcap.com>

### CODE REVIEW

**Comment by siddontang** [comment]
Please sign the CLA @choleraehyq

**Comment by choleraehyq** [comment]
@siddontang Done.

**Comment by siddontang** [comment]
LGTM

PTAL @BusyJay

**Comment by choleraehyq** [comment]
@siddontang Merge?

**Pull request merged**
