### PR TITLE
[DNM] raft: cache progress ids to avoid frequent copy

### PR DESCRIPTION
**Pull request by siddontang**
Now for every bcast, we have to clone all progress IDs, this is wasteful. We can cache the progress IDs and use them directly, no need to another clone. 

I write a simple test to bench:

```rust
#![feature(test)]

extern crate test;
extern crate flat_map;


#[cfg(test)]
mod tests {
    use test::{self, Bencher};
    use flat_map::FlatMap;
    
    #[bench]
    fn bench_flatmap_keys(b: &mut Bencher) {
        let mut m = FlatMap::with_capacity(3);
        m.insert(1, 1);
        m.insert(2, 2);
        m.insert(3, 3);

        b.iter(||{
            let ids: Vec<_> = m.keys().cloned().collect();
            test::black_box(ids);
        });
    }

    #[bench]
    fn bench_keys(b: &mut Bencher) {
        let m = vec![1, 2, 3];

        b.iter(||{
            let ids: Vec<_> = m.clone();
            test::black_box(ids);
        });
    }

    #[bench]
    fn bench_option_keys(b: &mut Bencher) {
        let mut m = Some(vec![1, 2, 3]);

        b.iter(||{
            let ids = m.take().unwrap();
            test::black_box(&ids);
            m = Some(ids);
        });
    }    
}
```

The result:

```
test tests::bench_flatmap_keys ... bench:          36 ns/iter (+/- 0)
test tests::bench_keys         ... bench:          33 ns/iter (+/- 1)
test tests::bench_option_keys  ... bench:          12 ns/iter (+/- 1)
```

The performance of caching IDs is better. Because bcast is a very frequent operation, I think this optimization is worthful.

PTAL @BusyJay @javaforfun @overvenus

### CODE REVIEW

**Comment by BusyJay** [comment]
How about make `send`, `send_heartbeat` and `send_append` not methods any more? So clone and cache are not necessary.

**Comment by siddontang** [comment]
> How about make send, send_heartbeat and send_append not methods any more? 

Using Macro? I doubt this may not fix the origin reference problem and will change the codes a lot, not a good idea now.

**Comment by BusyJay** [comment]
One way is define them as function, the other way is seperate `prs` and `messages` from `Raft`. So they won't affect each other.

**Comment by siddontang** [comment]
I guess these may also change raft codes a lot, maybe you can try it later.

**Pull request closed without merging**
