### PR TITLE
endpoint: reduce slow log

### LINKED ISSUE #2505: adjust coprocessor and scheduler slow timer
Now the slow timer for the coprocessor and scheduler operation contains the wait time + execution time. If one operation is too slow, it will cause following operations slow too, and the slow log is very difficult for us to see whether the operation is the real slow operation.

We should use the slow timer for the execution time, use metric for the wait time is enough.

### PR DESCRIPTION
**Pull request by BusyJay**
Now the waiting time is not considered any more.

close #2505

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
you can cherry pick to release @BusyJay

**Comment by BusyJay** [comment]
I will do it when 1.0.4 is about to be released.

**Pull request merged**
