### PR TITLE
build/ci: Use rust-toolchain file

### PR DESCRIPTION
**Pull request by csmoe**
Closes https://github.com/pingcap/tikv/issues/3066

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @csmoe 

LGTM

**Comment by breeswish** [comment]
I guess we don't need to specify toolchain overrides once we have `rust_toolchain`. According to the documentation, it is handled automatically.

**Comment by csmoe** [comment]
@breeswish yep, I read the doc before PR, but `rustup` doesn't guarantee the default toolchain is auto-set with `rust-toolchain`.

 I'll file a feature request for `rustup`, so block this PR firstly.

**Comment by Hoverbear** [comment]
Oh no :see_no_evil: I did this as well during the rust version upgrade. You did a great job though. :+1:

**Comment by BusyJay** [comment]
The file was added in #3208, closing this. Thanks for your contributions!

**Pull request closed without merging**
