### PR TITLE
[DNM] server, raftstore: add network monitoring

### PR DESCRIPTION
**Pull request by hhkbp2**
This PR tries to fix issue #1429 

Since there is a restriction about deployment of new process, it's only possible to implement the network monitoring as one component of the TiKV process. 

This PR adds a new worker to monitor the connection status between local store and remote stores in the server layer. The worker receives remote store ids from raftstore, and tries to track the connection status periodically. Currently it outputs log messages if the connections to remote stores are lost. Further extension to track all the bandwidth/latency/jitter and any other network indexes could be carried out in the future.

It's unusual to bind this fundamental monitoring to the main server process. There is still many issues about it, e.g. it requires a powerful database to store the great mount of monitoring data (and the corresponding network bandwidth to upload data) to track the networking between stores. And it would affect the performance of TiKV more or less.

### CODE REVIEW

**Comment by BusyJay** [comment]
This is too complicated. I think hook the message in `conn.rs` is enough.

**Comment by hhkbp2** [comment]
The basic idea is to separate the the monitoring and the normal store messages. It is important to decouple the normal store communication and this monitoring due to clarity, so that there will be coupling to disturb the implementation of new feature, such as coalesced heartbeat, quiesce request.

On The other hand, the implementation of network monitoring will be unprimitive if more features are added. It's better to separate it for normal messages considering the complexity.

**Comment by BusyJay** [comment]
I don't think attaching a timestamp to message will disturb any new features' implementation. No complex monitoring feature is about to be made in the near future, which should be monitored by the professional tools.

**Comment by siddontang** [comment]
I think ping/pong is ok, but I don't think we need so complex solution. 

+ We don't need to pass network monitor to raftstore, raftstore should not know this.
+ I see that you use a timer in raftstore, why not using this in server event loop directly? Embedding in raftstore doesn't decouple anything.
+ When server receives the Ping message, it can send Pong message directly in server event loop. 
+ If you want to use another thread to do this, you can use the block connection, send the Ping to a store and try to receive the Pong message, if timeout, log an error.

**Comment by hhkbp2** [comment]
There is no need to do network monitoring in TiKV. Close PR.

**Pull request closed without merging**
