### PR TITLE
pd: deny http prefix

### PR DESCRIPTION
**Pull request by BusyJay**
Currently configuration accepts both *host:port* and *http://host:port*, and save with "http://" prefix in memory then remove the "http://" prefix when connecting to remote. I propose to just deny "http://" prefix to make things clear and simple.

### CODE REVIEW

**Comment by siddontang** [comment]
But we may support https, how to handle it later?

**Comment by BusyJay** [comment]
This can be controlled through additional configuration entries. In fact, we at lease need an additional "cert" configuration to enable SSL support.

**Comment by siddontang** [comment]
LGTM

PTAL @overvenus

**Comment by overvenus** [comment]
It is a breaking change, clusters using "http://..." may fail to update to the latest tikv, if it is merged to master.

**Comment by BusyJay** [comment]
Yes. And more configuration refactoring is coming, it's going to be broken.

**Comment by siddontang** [comment]
If not compatibility, send to pre-ga branch.

**Comment by BusyJay** [comment]
FYI, TiDB also denies "http://" prefix.

**Comment by siddontang** [comment]
LGTM

PTAL @disksing

**Pull request merged**
