### PR TITLE
raftstore: update compact config.

### PR DESCRIPTION
**Pull request by disksing**
Increase `REGION_COMPACT_DELETE_KEYS_COUNT` to 1,000,000. Also remove it from config-template.

Fix https://github.com/pingcap/tikv/issues/1236

@zhangjinpeng1987

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
LGTM

**Comment by zhangjinpeng1987** [comment]
Maybe we should use another worker to do manual compaction.

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
Please use another worker to do manual compaction， in case we block the current runner.

**Comment by disksing** [comment]
@zhangjinpeng1987 @ngaut  I'll send another PR later.

**Pull request merged**
