### PR TITLE
reverse seek write include equal key

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
@disksing @BusyJay PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @BusyJay

**Comment by ngaut** [comment]
Is this a bug ?

**Comment by zhangjinpeng1987** [comment]
@disksing Please explain why `reverse_seek_write` works correctly before?

**Comment by disksing** [comment]
@ngaut 
When we want to check a txn is committed, we seek write cf for its commit record. If it is already rolled back, `get_commit_ts` will always return false no matter we get the commit record or not.
Now we have `reverse_seek_le` interface, switch to it will be more clear.

**Comment by BusyJay** [comment]
LGTM

**Comment by siddontang** [comment]
can we merge it now? @zhangjinpeng1987

**Pull request merged**
