### PR TITLE
coprocessor: rename thread name to `corpocessor-pool`

### PR DESCRIPTION
**Pull request by siddontang**
@BusyJay @hhkbp2 @zhangjinpeng1987

### CODE REVIEW

**Comment by hhkbp2** [comment]
LGTM

**Comment by BusyJay** [comment]
Actually, endpoint is a more specific name in this case, you can't tell if it's an `endpoint-pool` or an `observer-pool` just from the name `coprocessor-pool`.

**Comment by siddontang** [comment]
I think coprocessor here is more clear for our case. What does the endpoint or observer mean? When I first tried to find the CPU usage, I wanted to find the name with coprocessor, not observer and endpoint. 

Btw, there is a `end-point-worker` thread, what's the different with `endpoint-pool`, I am very confused with them.

**Comment by BusyJay** [comment]
There are two different kind of coprocessors in our project: endpoint and observer. Endpoint is a snippet that triggered by RPC and act like a store procedure, `TiDbEndPoint` for example. Observer is some handlers that are triggered by some internal events, `SplitObserver` for example. 

I think `end-point-worker` maybe better renamed to `endpont-scheduler`. What confuses you is the difference between worker and pool rather than coprocessor and endpoint.

**Comment by siddontang** [comment]
I guess nearly all of us will treat this as the coprocessor thread pool. In Grafana, we even name the metric panel with `Coprocessor`, it makes more scene.

**Comment by BusyJay** [comment]
>we even name the metric panel with Coprocessor

Then the name is not very accurate.

> it makes more scene.

How? Does it mean that if` SplitObserver` needs to schedule scan operation, it should be scheduled to `coprocessor-pool`？

**Comment by siddontang** [comment]
> Then the name is not very accurate

I think coprocessor is more commonly named for us, so it is ok. 

Why `SplitObserver` needs to scheduler to `coprocessor-pool`? `SplitObserver` is bind to raftstore, and if later, if we need a observer to run in a corpocessor pool, why can't?

**Comment by siddontang** [comment]
I find that there is a `end-point-concurrency` configuration, so it is not change the name directly. I will close it.

**Comment by siddontang** [comment]
But I still think `coprocessor` is more better here. 

We can have the concept `endpoint` and `observer`, and we can also have a `coprocessor-pool` to handle them, it is sensible. And most of us now have already treated the thread as `coprocessor` thread.

**Comment by BusyJay** [comment]
All the variables and codes are named properly and clearly to distinguish two concepts here, and the `endpiont-pool` is used by the `TiDBEndpoint` only (pool is not sync). I still don't see the point why change it to `coprocessor-pool`.

**Pull request closed without merging**
