### PR TITLE
[WIP] Changes to upgrade the mio version (in support of ppc64le)

### PR DESCRIPTION
**Pull request by seth-priya**
Using the deprecated mio APIs, based on the discussion here:
https://github.com/pingcap/tikv/issues/1965

Please review - thanks!

### CODE REVIEW

**Comment by seth-priya** [comment]
warnings are being treated as errors @ circleci - these are related to introduction and use of deprecated mio APIs

**Comment by siddontang** [comment]
/cc @BusyJay 
Do we have any way to ignore this warning?

Maybe we should use new mio directly later.

**Comment by seth-priya** [comment]
Hi @siddontang, @BusyJay, any thoughts on this? Thanks!

**Comment by siddontang** [comment]
Thanks @seth-priya

But CI still failed. :sob:
We should think a way to ignore the warning. any idea? @BusyJay

**Comment by BusyJay** [comment]
`allow` the lint should fix the warning. But I'm quite worry about the performance. Last time I check, when upgrading mio, performance of channel is 3 times slower. Maybe it's better to drop the mio dependency.

**Comment by seth-priya** [comment]
Thanks @siddontang @BusyJay for you response.

 I understand the concerns here and have been thinking about your suggestion to remove the dependency on mio and feel that I may not (at least at this point) have sufficient knowledge of the tikv codebase to implement and understand the implications / impact of a major change like this.

So, wanted your thoughts on it. I was wondering if, in case there are already some code changes for this from a previous effort, I may be able to pick them up and test them on Power. If not, I would need your guidance on what could be the best way forward on this. 

As I mentioned earlier, this would actually be the last change to support ppc64le architecture. 

Any thoughts? 

Thanks!

**Comment by siddontang** [comment]
Sorry for the late reply, @seth-priya 

@BusyJay and I decided to use std channel directly, the pseudo code like:

```rust
for {
    if let(Ok(msg)) = rx.recv_timeout(1s) {
        do_msg_here()
    }
    
    on_tick() 
}

on_tick() {
     // do the origin thing like raftstore tick does.
     
     // check timer 
}
```

Using std channel is simple and we think the hardest thing is to support timer, but it is also simple, we can use an std BinaryHeap. In check timer, we try to peek the heap and to see whether the next timer is expired or not, if expired, we pop the timer and handle it.

**Comment by siddontang** [comment]
@seth-priya 

In our test, although std channel is still slower than origin 0.5 mio channel, it is faster than 0.6 mio channel.

**Comment by seth-priya** [comment]
Hi @siddontang - thanks for looking into this and for the detailed response. So, just to be sure that I understand clearly, I should look at the rest of the changes to implement this (std channel)?

Thanks again!

**Comment by siddontang** [comment]
@seth-priya, it is very appreciated that you can support this feature.  :-) 

If you have any problem, you can tell us directly. 

/cc @BusyJay

**Comment by seth-priya** [comment]
@siddontang @BusyJay - no issues, I will start looking at this and get back with any questions / doubts that I may get.

**Comment by seth-priya** [comment]
Hi @siddontang - looking into this now, Based on what I understand, so far, we need to do some of the following:
1- use https://doc.rust-lang.org/std/sync/mpsc/ interfaces instead of mio
2- Replace mio EventLoop implementation and make corresponding changes - this will be one of the major changes
3- Referring to changes done for this PR - https://github.com/pingcap/tikv/pull/1691/commits/fa118e817f02ccbd0a383acae88074a1bbc2cf62
it seems there are parts in the code where we have made such changes? I believe we can refer to such changes, wherever applicable?

Just wanted to check if I started on the right track and this is what we are expecting? Thanks!

Regards,
Priya

**Comment by siddontang** [comment]
Thanks @seth-priya 

Your understanding is right, what we need to do is using channel to replace mio.

But we should notice that the previous Scheduler didn't have any timer but raftstore has, we should also implement a simple timer too.

**Comment by seth-priya** [comment]
I believe that this is no longer relevant as the plan is now to remove dependency on mio. 

This is tracked by https://github.com/pingcap/tikv/issues/2516 and PRs/issues raised as part of that - will create new PRs for raftstore refactoring and any further work required to address these issues or any other ppc64le specific changes.

**Pull request closed without merging**
