### PR TITLE
cherry pick release-2.0: apply hot fix for murmur3

### PR DESCRIPTION
**Pull request by breeswish**
@BusyJay @lamxTyler PTAL

### CODE REVIEW

**Comment by BusyJay** [comment]
This is unnecessary, just fast forward.

**Comment by breeswish** [comment]
you mean cheery pick into that branch without a PR?

**Comment by BusyJay** [comment]
I mean merge fast forward. release-2.0 is going to be the same as master until ga.

**Comment by breeswish** [comment]
I think recent changes in master is supposed to be under version rc2 or other, not rc1? currently we only want to apply this fix to rc1.

**Comment by BusyJay** [comment]
rc1 is released, there is no such `apply this fix to rc1` thing.

**Comment by breeswish** [comment]
shall we close this PR?

**Pull request closed without merging**
