### PR TITLE
bench: Add bench of simulated transactional operations on rocksdb engine

### PR DESCRIPTION
**Pull request by MyonKeminta**

### CODE REVIEW

**Comment by siddontang** [comment]
why not bench storage MvccTxn API directly, so you don't need to implement the same logic again.

**Comment by zhangjinpeng1987** [comment]
I think operating directly on rocksdb and use MvccTXN API are two different benches. We can easily sketch out our new ideas on txn using bench directly on rocksdb. But when it comes to MvccTXN API, we can't.

**Comment by siddontang** [comment]
Benching RocksDB is another thing, here I want to know is what the performance of our current transaction implementation.

**Comment by MyonKeminta** [comment]
..or is it ok to bench SyncStorage?

**Comment by zhangjinpeng1987** [comment]
`Benching RocksDB is another thing, here I want to know is what the performance of our current transaction implementation.`
Another pr?

**Pull request closed without merging**
