### PR TITLE
storage: support cf for rawkv.

### PR DESCRIPTION
**Pull request by disksing**
Support specifying _ColumnFamily_ in the rawkv APIs. 
If cf is not specified in the request, CF_DEFAULT is used by default, so this feature is backward compatible.

### CODE REVIEW

**Comment by siddontang** [comment]
please add description for this PR.

**Comment by siddontang** [comment]
LGTM

**Comment by huachaohuang** [comment]
Can we use an enum for the cf name, since we only have a few valid cf?

**Comment by disksing** [comment]
@huachaohuang In the future we may allow users to customize CFs or even create CFs dynamically.

**Comment by wentaoxu** [comment]
LGTM

**Comment by siddontang** [comment]
@disksing 

I think we can go on now.

**Comment by disksing** [comment]
PTAL @siddontang @wentaoxu

**Comment by breeswish** [comment]
LGTM.

**Pull request merged**
