### PR TITLE
[WIP] add recurse guard

### PR DESCRIPTION
**Pull request by BusyJay**

### CODE REVIEW

**Comment by iamxy** [comment]
/run-integration-compatibility-test tidb=release-1.0 tidb-test=1.0.0

**Comment by iamxy** [comment]
/run-integration-compatibility-test tidb=release-1.0 tidb-test=1.0.0

**Comment by BusyJay** [comment]
/run-integration-compatibility-test tidb=release-1.0 tidb-test=1.0.0

**Pull request closed without merging**
