### PR TITLE
dag/expr: return unknown signature error for unimplemented signatures

### PR DESCRIPTION
**Pull request by AndreMouche**
## What have you changed? (mandatory)
Hi,
    This PR returns unknow signature error for those unimplemented signatures.

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)

unit test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

@hicqu @breeswish PTAL

### CODE REVIEW

**Comment by breeswish** [comment]
LGTM. I think tests are not needed. We actually don't want those unimplemented functions to be really "unimplemented" forever.

**Comment by BusyJay** [comment]
This pr changes the behavior of some signatures from panicking to report error. With tests how to ensure it is working as expected?

**Comment by AndreMouche** [comment]
tests added, @breeswish @BusyJay PTAL

**Pull request merged**
