### PR TITLE
pin level0 filter and index blocks

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**

### CODE REVIEW

**Comment by siddontang** [comment]
Do we need to support optimize_filters_for_hits for default CF too?

**Comment by zhangjinpeng1987** [comment]
Default cf is included.

**Comment by siddontang** [comment]
PTAL @huachaohuang

**Comment by siddontang** [comment]
> Default cf is included.

I can't find it. @zhangjinpeng1987

**Comment by siddontang** [comment]
CI failed

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tikv/pull/2288/files#diff-6d8a5e2104954a026de2bfe2b936aea4R125

**Pull request merged**
