### PR TITLE
readme: correct some mistake in tikv stack image.

### PR DESCRIPTION
**Pull request by c4pt0r**
region number

### CODE REVIEW

**Comment by c4pt0r** [comment]
@ngaut @qiuyesuifeng @iamxy PTAL

**Comment by siddontang** [comment]
Now node has only one store, so the stack image is not correct now.

**Comment by ngaut** [comment]
@siddontang If the node is a process, i think it's correct.

**Comment by c4pt0r** [comment]
@ngaut I think the node is a physical machine.

**Comment by siddontang** [comment]
LGTM

**Comment by c4pt0r** [comment]
@qiuyesuifeng

**Comment by qiuyesuifeng** [comment]
LGTM

**Pull request merged**
