### PR TITLE
Cargo.toml: Update version from 1.0.3 to 1.0.4

### PR DESCRIPTION
**Pull request by shenli**
We will release 1.0.4 soon.

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by disksing** [comment]
Need to update `Cargo.lock` too. (section pacakge with name tikv)

**Comment by BusyJay** [comment]
Should wait till #2571

**Comment by BusyJay** [comment]
LGTM

**Comment by shenli** [comment]
/run-integration-tests tidb=release-1.0 pd=release-1.0 tidb-test=release-1.0

**Pull request merged**
