### PR TITLE
config: adjust label checks

### PR DESCRIPTION
**Pull request by BusyJay**
Labels are case-insensitive, so accept upper case too.

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by huachaohuang** [comment]
I think we should wait for PD to finish the case-insensitive conversion.

**Comment by siddontang** [comment]
PTAL @huachaohuang @disksing

**Comment by overvenus** [comment]
CC https://github.com/pingcap/pd/pull/794

**Comment by siddontang** [comment]
Ping @disksing

**Pull request merged**
