### PR TITLE
tests: remove redundant storage tests

### PR DESCRIPTION
**Pull request by overvenus**
Some storage tests are tested twice, one in the `integrations` and the other in the `failpoints`. This PR removes those redundant tests.

CC #2642 and #2643.

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
CI failed @overvenus

**Comment by siddontang** [comment]
PTAL @BusyJay

**Comment by overvenus** [comment]
It's not relevant to the PR, I have reported it. @siddontang
/run-all-tests

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
