### PR TITLE
raftstore: support configure election range

### PR DESCRIPTION
**Pull request by BusyJay**
ref pingcap/raft-rs#63.

### CODE REVIEW

**Comment by siddontang** [comment]
em, now increasing the election timeout to a larger value is enough?

**Comment by BusyJay** [comment]
election timeout is also used as the least of raft itself, which may cause the node rejects all vote requests for a long time.

**Comment by BusyJay** [comment]
PTAL

**Comment by siddontang** [comment]
PTAL @hicqu @overvenus

**Comment by hicqu** [comment]
LGTM.

**Comment by BusyJay** [comment]
PTAL

**Pull request merged**
