### PR TITLE
config: enable table split by default.

### PR DESCRIPTION
**Pull request by disksing**

### CODE REVIEW

**Comment by BusyJay** [comment]
We should wait #2502.

**Comment by siddontang** [comment]
@BusyJay @disksing 

If the adjacent empty regions are for different two tables and we ensure the tables are empty, can we merge these regions?

**Comment by disksing** [comment]
@siddontang We can merge them only if table-split is off.
@BusyJay Why? I don't think it depends on merge.

**Comment by siddontang** [comment]
LGTM

I think we can support table split by default, but we should also need to consider the empty table region problem later.

**Comment by siddontang** [comment]
Do we still need to do this? @disksing

**Comment by siddontang** [comment]
ping @disksing

**Comment by disksing** [comment]
Of cause need it. PTAL @overvenus

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
