### PR TITLE
*: pick raft update

### PR DESCRIPTION
**Pull request by BusyJay**
This is part of v2.0.1

### CODE REVIEW

**Comment by BusyJay** [comment]
/run-all-tests tidb=release-2.0 pd=release-2.0 tidb-test=release-2.0

**Comment by overvenus** [comment]
It looks like missing `sync-log` backward compatibility. https://github.com/pingcap/tikv/pull/3045/files#diff-4fe7d196e1e0c8626e9abc9ffdb98ef2R1876

**Comment by BusyJay** [comment]
They are checked in `PeerStorage::append` instead of sending messages.

**Comment by overvenus** [comment]
I mean 2.0.1 sends to 2.0.0.

**Comment by BusyJay** [comment]
I thought about it before. In fact, we can only guarantee that higher version of TiKV can handle lower version of TiKV correctly, but can't the opposite way. For example, when adding a new command or flags, we can't guarantee that old version of TiKV can also recognize it and handles it as intended. That was the reason I chose to make it simple.

**Comment by siddontang** [comment]
If we really do the downgrade, the lower version can't handle this flag but can still use sync-log. Of course, there is a risk that the lower version can't do some sync work explicitly for some logs, mostly,  it is fine.

So LGTM 

PTAL @overvenus @hicqu

**Pull request merged**
