### PR TITLE
raftstore: sync snapshot

### PR DESCRIPTION
**Pull request by UncP**

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by BusyJay** [comment]
This change may block snap receiving thread and lead to OOM probably. How to deal with this situation?

**Comment by UncP** [comment]
Is it ok to sync data while writing snapshot, instead of sync entire file when writing is finished?

**Comment by ngaut** [comment]
It's just a meta file, flush operation should be very fast.

**Comment by UncP** [comment]
Yes, meta file is fine, but there are snapshot files too.

**Comment by ngaut** [comment]
Do we have any tests? Is this a real problem or just concern ?

**Comment by UncP** [comment]
@BusyJay

**Comment by BusyJay** [comment]
This is a new changes, so it's just a concern for now. We need to add test cases for this changes.

**Comment by siddontang** [comment]
I guess flushing meta is enough. Here we just need to ensure the meta data is correct. 

And we also have to handle the scenario that snapshot is corrupted.

**Pull request merged**
