### PR TITLE
pd: add get_region_by_id()

### PR DESCRIPTION
**Pull request by huachaohuang**

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed @huachaohuang

**Comment by huachaohuang** [comment]
Leave this until [PD #329](https://github.com/pingcap/pd/pull/329) has been merged.

**Comment by siddontang** [comment]
LGTM

**Comment by huachaohuang** [comment]
@hhkbp2 PTAL

**Comment by hhkbp2** [comment]
LGTM

**Pull request merged**
