### PR TITLE
util: add file name and line number for box error

### PR DESCRIPTION
**Pull request by BusyJay**
So we can inspect what causes the problem instead of seeing a context-less error.

### CODE REVIEW

**Comment by BusyJay** [comment]
@wentaoxu @zhangjinpeng1987 please make sure that tidb-client doesn't depend on the format of error message.

**Comment by wentaoxu** [comment]
LGTM, ticlient only rely on the error message like this `strings.Contains(err.Error(), "try again later")`, I think this is not related.

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
