### PR TITLE
store/util: sleeps longer than lease

### PR DESCRIPTION
**Pull request by overvenus**
Clocks may be unstable in VMs, so let's sleep longer.

Fixes https://github.com/pingcap/tikv/issues/3044

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
Maybe deeper reason need to be investigated. Does it mean that TiKV should not be deployed on virtual machine? If not why the tests fail on Circle CI? What can we do to prevent such failure?

**Comment by siddontang** [comment]
any update?

**Comment by BusyJay** [comment]
It seems that what `sleep` use is CLOCK_MONOTONIC, which can be subject to NTP adjustments. And what we use to calculate lease is CLOCK_MONOTONIC_RAW, which can't be adjusted. So can it be solved by forcing a ntp update before running any tests?

**Comment by siddontang** [comment]
I think here only knowing that monotonic and monotonic raw are different is enough, even we forcibly update NTP, we still may not guarantee they are the same all the time.

Here I prefer adding a comment or use a small gap (not 500 ms) to work around it.

**Comment by BusyJay** [comment]
> ...we still may not guarantee they are the same all the time.

Why? From the manual:

> Similar to CLOCK_MONOTONIC, but provides access to a raw hardware-based time that is not subject to NTP adjustments or the incremental adjustments performed by adjtime(3).

**Comment by siddontang** [comment]
If we can guarantee monotonic and monotonic raw are same, why does raw exist?

another problem is that when do we do the adjust? The NTP maybe still be adjusted later even we updated before? Do we need to adjust NTP every time before sleep? 

Here I think knowing they are different is enough.

**Comment by BusyJay** [comment]
> .. why does raw exist?

The statement I quoted explains why raw exists.

> another problem is that when do we do the adjust? The NTP maybe still be adjusted later even we updated before? Do we need to adjust NTP every time before sleep?

Just run ntpdate before running tests in CI. Not every case can be fixed, just like 500ms can't be guaranteed to be enough. Updating the time first to make the adjustment more unlikely to happen. If it fixes the failure, then I prefer this way as stronger constraint/test case lead to safer code.

**Comment by AndreMouche** [comment]
Any update? The test failed frequently on CI
```
test raftstore::store::util::tests::test_lease ... thread 'raftstore::store::util::tests::test_lease' panicked at 'assertion failed: `(left == right)`
  left: `Valid`,
 right: `Expired`: elapsed monotonic_raw: Duration { secs: 1, nanos: 499796590 }, monotonic: Duration { secs: 1, nanos: 500115212 }', src/raftstore/store/util.rs:439:13
```

**Comment by BusyJay** [comment]
Any updates? CI check of #3137 fails due to similar error.

**Comment by BusyJay** [comment]
Can this be closed now?

**Pull request closed without merging**
