### PR TITLE
raft: check leader request when become_follower after recv msg with higher term

### PR DESCRIPTION
**Pull request by javaforfun**
see https://github.com/coreos/etcd/issues/8553 and https://github.com/coreos/etcd/pull/8339

### CODE REVIEW

**Comment by siddontang** [comment]
seem the etcd doesn't merge these PRs.

**Comment by javaforfun** [comment]
https://github.com/coreos/etcd/pull/8339  already merged

**Comment by siddontang** [comment]
Cool

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
