### PR TITLE
bin/util: rocksdb compression per level configurable and tuning rocksdb options to fit common cases.

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
rocksdb: compression per level configurable and tuning rocksdb options to fit common cases.

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@ngaut @siddontang @BusyJay @disksing PTAL

**Comment by ngaut** [comment]
LGTM

**Comment by zhangjinpeng1987** [comment]
PTAL

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
