### PR TITLE
raftkv: move read outside of raft thread.

### PR DESCRIPTION
**Pull request by ngaut**

### CODE REVIEW

**Comment by ngaut** [comment]
PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by tiancaiamao** [comment]
should we clean code of on_request in server/kv.rs to represent this change?

**Comment by ngaut** [comment]
Not now. We will clean up the raft store once we rewrite get and seek in tests.

**Comment by ngaut** [comment]
PTAL  @BusyJay

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
