### PR TITLE
*: Skip printing stracktrace when using panic::recover

### PR DESCRIPTION
**Pull request by BusyJay**
@ngaut @siddontang

### CODE REVIEW

**Comment by siddontang** [comment]
can using set_handler do this too? I think it is more clear and easy. 

https://github.com/rust-lang/rust/issues/30449

**Comment by BusyJay** [comment]
`set_hook` is formerly called `set_handler`. :)

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
@ngaut PTAL

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
