### PR TITLE
[WIP] *: save index data in seperated cf.

### PR DESCRIPTION
**Pull request by disksing**

### CODE REVIEW

**Comment by siddontang** [comment]
I will change the PR base to pre-ga.

**Comment by siddontang** [comment]
should add the cf configuration in the config file.

**Comment by siddontang** [comment]
Any performance improvement in the benchmark? @zhangjinpeng1987

**Comment by siddontang** [comment]
can we close it? @zhangjinpeng1987 @disksing

**Comment by disksing** [comment]
No use. Close it for now.

**Pull request closed without merging**
