### PR TITLE
pd/etcd: fix hyper client

### PR DESCRIPTION
**Pull request by huachaohuang**
Hyper async client queues the request handlers and call the first handler on the first response.
But this will be a problem if we do not handle responses in order.
So we reuse the hyper client only if we complete the request/response.

ref #956

### CODE REVIEW

**Comment by huachaohuang** [comment]
This will cause infinite timeout if we start TiKV before PD.

**Comment by BusyJay** [comment]
Do we need to report the issue to hyper project?

**Comment by huachaohuang** [comment]
ref https://github.com/hyperium/hyper/issues/901

**Comment by siddontang** [comment]
I think we can remove hyper pd client now.

**Comment by siddontang** [comment]
Now we don't need to get pd leader first.

**Comment by huachaohuang** [comment]
OK, close here and remove hyper client in another PR.

**Pull request closed without merging**
