### PR TITLE
*: fix ts generators in tests

### PR DESCRIPTION
**Pull request by disksing**
A complement for #558 
@BusyJay @ngaut

### CODE REVIEW

**Comment by BusyJay** [comment]
`ts_generator` in `bench_tombstone_scan` needs to be updated too.

**Comment by BusyJay** [comment]
LGTM

**Comment by ngaut** [comment]
Using constant instead of 1000000.

**Comment by disksing** [comment]
@ngaut PTAL.

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
