### PR TITLE
remove bloom for raft cf

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
In most cases raft entries can get from memtable, in another special case that raft log lag is large, scan will used. So bloom filter for raft cf is redundant.

### CODE REVIEW

**Comment by javaforfun** [comment]
LGTM

**Comment by siddontang** [comment]
Maybe we should increase the memtable size, 128 MB seems a little small.

**Comment by lishihai9017** [comment]
LGTM

**Comment by zhangjinpeng1987** [comment]
@siddontang As I have tested, 128MB is enough for most cases, on the other hand it is configurable.

**Pull request merged**
