### PR TITLE
Switch to use static metrics for more metrics

### PR DESCRIPTION
**Pull request by breeswish**
- [x] Waiting for PR merge: https://github.com/pingcap/rust-prometheus/pull/166
- [x] Waiting for PR merge: https://github.com/pingcap/rust-prometheus/pull/169
- [x] Benchmark

### CODE REVIEW

**Comment by breeswish** [comment]
Inspected around 3% improvement in every storage ops.

**Comment by siddontang** [comment]
Cool

**Comment by siddontang** [comment]
how about context switch?

**Comment by BusyJay** [comment]
@overvenus @hicqu PTAL

**Comment by breeswish** [comment]
Too old. Will open a new PR.

**Pull request closed without merging**
