### PR TITLE
[DNM]allow commit even if there are rollback records

### PR DESCRIPTION
**Pull request by wentaoxu**
this pr is used to promote performance for conflict transactions. we allow prewrite happen even if there are rollback records.
for two txn `tx1` and `tx2`, if start_ts(tx1) > start_ts(tx2), and they act like this
```
       tx1            |            tx2
                      |         get start_ts
 get start_ts         |
    select            |           select
    prewrite          |         
    rollback          |   
                      |          prewrite
                      |          commit -- this will fail before this pr
```
PTAL @disksing @zhangjinpeng1987 @AndreMouche @ngaut

### CODE REVIEW

**Comment by ngaut** [comment]
Please describe your purpose of the PR. Not just what you do.

**Comment by wentaoxu** [comment]
@ngaut ok

**Comment by zhangjinpeng1987** [comment]
Please give bench result.

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/tikv/pull/3290 prewrite is not allowed if exist commit version whose commit timestamp is larger than or equal to prewrite's start timestamp, even when the commit type is rollback.

**Pull request closed without merging**
