### PR TITLE
Fixes #1015: call release_lock() in Scheduler::on_read_finished().

### LINKED ISSUE #1015: Scheduler: read commands have no corresponding self.release_lock() for self.acquire_lock()
What did you expect to see?

[/storage/txn/scheduler.rs](https://github.com/pingcap/tikv/blob/master/src/storage/txn/scheduler.rs):
Even though no latches are required for read commands, release_lock() and acquire_lock() should always match, otherwise the code is not generic and error-prone. Prefer calling self.release_lock() in on_read_finished() explicitly to mark the completion of command.

### PR DESCRIPTION
**Pull request by weidagang**

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Comment by disksing** [comment]
@weidagang Thanks for you contribution. But in scheduler, read only command does not acquire locks so it does not need to unlock.

**Comment by weidagang** [comment]
@disksing thanks for figuring it out, but my point is acquire and release should always come in pair, since every command has gone through acquire, it makes sense to call release too.

An alternative is to explicitly avoid acquire_lock for read commands. But I prefer making acquire and release as no op to mark the start and completion.

**Comment by disksing** [comment]
@weidagang You are right. I didn't notice that we call `acquire_lock` for read only commands too. LGTM.

**Pull request merged**
