### PR TITLE
storage: rename the scheduler of txn to coordinator

### PR DESCRIPTION
**Pull request by Connor1996**
## What have you changed? (mandatory)
In storage mod, there are two concepts of `scheduler`, one for worker's `scheduler` and the other for txn `scheduler` which controls write concurrency and wraps a worker's `scheduler`. And this is somewhat confusing, so I rename the `scheduler` of txn to `coordinator` to distinguish them.

## What are the type of the changes? (mandatory)
- Improvement (non-breaking change which is an improvement to an existing feature)

## How has this PR been tested? (mandatory)
No need

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)
There some related configurations, but I don't change these names.
```
[storage]
# the number of slots in scheduler latches, concurrency control for write.
# scheduler-concurrency = 2048000

# scheduler's worker pool size, should increase it in heavy write cases,
# also should less than total cpu cores.
# scheduler-worker-pool-size = 4

# When the pending write bytes exceeds this threshold,
# the "scheduler too busy" error is displayed.
# scheduler-pending-write-threshold = "100MB"
```
I'm not sure it is necessary to change these `scheduler`, cause there is a `scheduler` still  in `coordinator` and these configuration names look fine for me. What's your opinion?

### CODE REVIEW

**Comment by breeswish** [comment]
Nice. Some thoughts:

- Change names in configs seems to be very reasonable. However you need to carefully treat compatibility issues.
- I think you also need to change scheduler worker thread names to something like `cood-normal` and `cood-high` --> because of this change, you need to change TiDB ansible as well.

**Comment by MyonKeminta** [comment]
Maybe some metrics' name should be updated as well.
And maybe there is some documents to be obsoluted..?

**Comment by MyonKeminta** [comment]
In my personal opinion, the name `Scheduler` of that part of txn is just fine. However, when I read the code for the first time, it astonished me that the sender part of `Worker` was also named `Scheduler`.

**Comment by Connor1996** [comment]
Thanks for advice, I find that there are a lot of metrics and documents involved and it will introduce compatibility issues. For the sake of historical burden, maybe we could rename it along with large refactor in the future. @breeswish @MyonKeminta

**Comment by Connor1996** [comment]
@MyonKeminta Seems `worker` and `scheduler` are used widely as convention in code,

**Pull request closed without merging**
