### PR TITLE
raftstore: enlarge default notify queue capacity

### PR DESCRIPTION
**Pull request by BusyJay**
Default capacity for notify queue is 4096, which is small when region count increase to more than 7000.

@ngaut @siddontang @disksing PTAL

### CODE REVIEW

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
@siddontang PTAL

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
