### PR TITLE
copr: aggr null for first

### PR DESCRIPTION
**Pull request by BusyJay**
ref: pingcap/tidb#2057

@siddontang @coocood PTAL

### CODE REVIEW

**Comment by coocood** [comment]
LGTM

**Comment by BusyJay** [comment]
@siddontang PTAL

**Comment by siddontang** [comment]
Seem not the same with the TiDB PR.

**Comment by BusyJay** [comment]
TiDB uses a flag to indicate if the result is set. But we use an Option already, no need to add an additional flag.

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
