### PR TITLE
bench: memtable get with/without bloom

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
```
test memtable::bench_memtable::bench_memtable_get_exist_32mb                ... bench:         923 ns/iter (+/- 165)
test memtable::bench_memtable::bench_memtable_get_exist_64mb                ... bench:         899 ns/iter (+/- 250)
test memtable::bench_memtable::bench_memtable_get_exist_with_bloom_32mb     ... bench:       1,028 ns/iter (+/- 525)
test memtable::bench_memtable::bench_memtable_get_exist_with_bloom_64mb     ... bench:         974 ns/iter (+/- 405)
test memtable::bench_memtable::bench_memtable_get_not_exist_32mb            ... bench:         822 ns/iter (+/- 129)
test memtable::bench_memtable::bench_memtable_get_not_exist_64mb            ... bench:       1,069 ns/iter (+/- 460)
test memtable::bench_memtable::bench_memtable_get_not_exist_with_bloom_32mb ... bench:         259 ns/iter (+/- 76)
test memtable::bench_memtable::bench_memtable_get_not_exist_with_bloom_64mb ... bench:         247 ns/iter (+/- 88)
```

We can see that if key not exist, memtable get with bloom filter is much more faster than memtable get without bloom filter.

@siddontang @lishihai9017 @javaforfun PTAL

### CODE REVIEW

**Comment by zhangjinpeng1987** [comment]
@ngaut PTAL

**Comment by zhangjinpeng1987** [comment]
`MVCC get` always call `load_lock` first, in most cases the lock is not exist, so add bloom filter for memtable of lock cf will benefit a lot.

**Comment by javaforfun** [comment]
LGTM

**Comment by ngaut** [comment]
This PR should not in TiKV repo, since it has nothing to do with TiKV, it's just a bench result for rocksdb.

**Comment by siddontang** [comment]
Do we need to move to rust-rocksdb? 

@zhangjinpeng1987

**Comment by zhangjinpeng1987** [comment]
move to github.com/pingcap/rust-rocksdb

**Pull request closed without merging**
