### PR TITLE
copr: always check fsp

### PR DESCRIPTION
**Pull request by BusyJay**
@ngaut @coocood @shenli @qiuyesuifeng PTAL

### CODE REVIEW

**Comment by BusyJay** [comment]
The default fsp is -1 which will be transmute to 255 when converting to u8. It may lead to index out of bound in some cases.

**Comment by coocood** [comment]
LGTM

**Comment by siddontang** [comment]
CI failed @BusyJay

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
