### PR TITLE
Fix test_server_clear_stale_data

### PR DESCRIPTION
**Pull request by huachaohuang**
This test sometime fails in CI, I'm not sure why yet. But I think it may relate
to the CF_RAFT, because CF_RAFT is writting while the test constructing the
necessary SST files. So I remove the CF_RAFT and CF_WRITE (so we don't need to
care about the SliceTransform).

### CODE REVIEW

**Comment by UncP** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @zhangjinpeng1987

**Comment by zhangjinpeng1987** [comment]
Why using mvcc key will fail?

**Comment by huachaohuang** [comment]
The fail is not caused by mvcc key, it may be caused by the CF_RAFT, I just remove the CF_WRITE and mvcc key by the way.

**Comment by UncP** [comment]
My understanding is that CF_RAFT should finish writing before constructing the sst files, but it didn't. Am I right?

**Comment by huachaohuang** [comment]
Well, the raft group is still working while the test is constructing the SST files, so other data will be written to the CF_RAFT, which is out of the test's control and may fail the test.

**Comment by siddontang** [comment]
Do we need to keep the Write CF here?

**Comment by huachaohuang** [comment]
I have no strong opinion about CF_WRITE, as long as CF_RAFT is removed.

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
