### PR TITLE
CI: Add CircleCI support

### PR DESCRIPTION
**Pull request by andelf**
- cargo support fix, via changing .gitconfig
- cache support, download rust only when nightly date changes
- pd-server from docker hub

### CODE REVIEW

**Comment by siddontang** [comment]
I think we can add the CI build status in README like tavis CI.

**Comment by andelf** [comment]
@siddontang 
according to https://circleci.com/docs/status-badges/ , an API token is needed. 
Only repo manager can do that.

**Comment by siddontang** [comment]
> according to https://circleci.com/docs/status-badges/ , an API token is needed.
Only repo manager can do that.

@ngaut

**Comment by ngaut** [comment]
Done!

**Comment by andelf** [comment]
@ngaut @siddontang PTAL

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
LGTM

**Pull request merged**
