### PR TITLE
[DNM]tikv-server: change rocksdb options for testing

### PR DESCRIPTION
**Pull request by tiancaiamao**

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by qiuyesuifeng** [comment]
@tiancaiamao  Can u show some benchmark information for comparison?

**Comment by tiancaiamao** [comment]
I'm working with some turning options and find bench testing panic, while it pass with the default option.
So, don't merge this PR, I'll go into some more detail.

**Comment by tiancaiamao** [comment]
I'm not quite figure out why changing the default rocksdb options  will make bench panic. 
help needed... PTAL @siddontang @ngaut

**Comment by tiancaiamao** [comment]
PTAL @siddontang @shenli  
change block_size and target_file_size_base now

**Comment by tiancaiamao** [comment]
I'll reopen this later, after bench pass and show turning options take effect.

**Pull request closed without merging**
