### PR TITLE
raft: simplify leadership transfer

### PR DESCRIPTION
**Pull request by tiancaiamao**
keep sync with etcd
https://github.com/coreos/etcd/pull/5313/files /cc @xiang90 
@siddontang @BusyJay @ngaut

### CODE REVIEW

**Comment by siddontang** [comment]
This PR has not merged in etcd yet. We should wait and then merge.

**Comment by xiang90** [comment]
Can someone review the code in etcd/raft? Then I can get it merged.

**Comment by xiang90** [comment]
the pr in etcd is merged

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
LGTM

**Pull request merged**
