### PR TITLE
raft: Enable prevote by default

### PR DESCRIPTION
**Pull request by Hoverbear**
Enables prevote by default.

We disabled prevote by default because we found some issues with it in some tests.

This PR enables prevote again by default.

Depends on:

* https://github.com/pingcap/raft-rs/pull/84
* #3255 .

## What are the type of the changes? (mandatory)

* Bug fix

## How has this PR been tested? (mandatory)

The CI

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

Nope

## Does this PR affect tidb-ansible update? (mandatory)

Nope

### CODE REVIEW

**Comment by Hoverbear** [comment]
@siddontang Yes it's because we turn on prevote in #3255, I posted a bit of investigation there. (https://github.com/pingcap/tikv/issues/3255#issuecomment-403158973)

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @BusyJay

**Comment by Hoverbear** [comment]
Seems we may not need #3265 now that #3255 is merged.

**Comment by BusyJay** [comment]
I don't think it's a good idea to enable it by default without the fix https://github.com/pingcap/raft-rs/pull/84.

**Comment by Hoverbear** [comment]
@BusyJay I agree. let's wait for https://github.com/pingcap/raft-rs/pull/92

**Comment by Hoverbear** [comment]
Raft 0.3.1 is released so now this can proceed.

**Comment by Hoverbear** [comment]
```
test raftstore_cases::test_merge::test_node_merge_brain_split ... thread 'raftstore_cases::test_merge::test_node_merge_brain_split' panicked at 'region id: 1000 end_key: "k2" region_epoch {conf_ver: 1 version: 2} peers {id: 1001 store_id: 2} peers {id: 1002 store_id: 1} peers {id: 1003 store_id: 3} is still not merged.', tests/raftstore/pd.rs:821:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Hmm... This is a different error than #2917.

**Comment by siddontang** [comment]
PTAL @BusyJay

**Comment by BusyJay** [comment]
@hicqu PTAL the fail learner case. I believe there is a bug either in tests or in the sources.

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
