### PR TITLE
Cherry pick several bug fixes

### PR DESCRIPTION
**Pull request by overvenus**

### CODE REVIEW

**Comment by siddontang** [comment]
LGTM

**Comment by siddontang** [comment]
CI failed @overvenus

**Comment by siddontang** [comment]
@overvenus CI still failed

**Comment by overvenus** [comment]
/run-integration-common-test tidb-test=release-1.0 tikv=release-1.0 tidb-private-test=release-1.0

**Comment by overvenus** [comment]
/run-integration-tests tidb=release-1.0 pd=release-1.0 tidb-test=release-1.0

**Comment by overvenus** [comment]
PTAL

**Comment by siddontang** [comment]
PTAL @BusyJay @disksing

**Pull request merged**
