### PR TITLE
use SSE by default.

### PR DESCRIPTION
**Pull request by siddontang**
SSE is supported in Intel and AMD CPU, so we can use it directly.

@iamxy @BusyJay @zhangjinpeng1987

### CODE REVIEW

**Comment by andelf** [comment]
Does this drop support for arm64?

**Comment by siddontang** [comment]
No, ARM is not in our official support.

**Comment by ngaut** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @andelf

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
