### PR TITLE
raft: port promotable checking for MsgTimeoutNow

### PR DESCRIPTION
**Pull request by hhkbp2**
Hi,

This PR port the promotable checking for MsgTimeoutNow from etcd/raft.
It substitutes #1356

### CODE REVIEW

**Comment by hhkbp2** [comment]
PTAL @siddontang @BusyJay

**Comment by siddontang** [comment]
LGTM

**Comment by ngaut** [comment]
Please fix CI

**Comment by hhkbp2** [comment]
PTAL @ngaut @BusyJay
The CI build failure before is caused by #1462, it's OK to merge this PR.

**Comment by BusyJay** [comment]
LGTM

**Pull request merged**
