### PR TITLE
expr/builtin_fncall: implement MultiplyIntUnsigned

### PR DESCRIPTION
**Pull request by AndreMouche**
## What have you changed? (mandatory)

This PR implements the scalar function MultiplyIntUnsigned

## What are the type of the changes? (mandatory)

The currently defined types are listed below, please pick one of the types for this PR by removing the others:
- New feature (non-breaking change which adds functionality)

## How has this PR been tested? (mandatory)

unit test

## Does this PR affect documentation (docs/docs-cn) update? (mandatory)

no

## Does this PR affect tidb-ansible update? (mandatory)

no

## Refer to a related PR or issue link (optional)

https://github.com/pingcap/tikv/issues/3275

The related source in tidb: https://github.com/pingcap/tidb/blob/master/expression/builtin_arithmetic.go#L532

@zz-jason @XuHuaiyu @breeswish PTAL

### CODE REVIEW

**Comment by breeswish** [comment]
LGTM! BTW I saw "MultiplyIntUnsigned" occurred in multiple places. Since we are already using macros, can we just eliminate it to one place to be more friendly to the contributor?

**Comment by AndreMouche** [comment]
Would you pull the request for it @breeswish ?

**Comment by breeswish** [comment]
@AndreMouche Love to!

**Pull request merged**
