### PR TITLE
[DNM] upgrade clippy to 0.0.145 and make tikv build with latest nightly

### PR DESCRIPTION
**Pull request by bailaohe**
build pass under rustc 1.21.0-nightly

### CODE REVIEW

**Comment by bailaohe** [comment]
well, the .travis.yml is not updated. Shall we update the nightly version?

**Comment by javaforfun** [comment]
we need a specific version, otherwise incompatible update may break us.

**Comment by siddontang** [comment]
Thanks @bailaohe 

We will decide a newer fixed rust version after we release RC4 version this week.

**Comment by siddontang** [comment]
#2146 does the same thing, I will close this PR.

Thanks @bailaohe

**Pull request closed without merging**
