### PR TITLE
Config: check ext4 nodelalloc

### PR DESCRIPTION
**Pull request by AndreMouche**
@overvenus @BusyJay PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
any test?

**Comment by MyonKeminta** [comment]
Why is libc upgraded?

**Comment by BusyJay** [comment]
I'm quite worry about whether it is nodelalloc that causes the problem. Please note that, nodelalloc is enabled by default, rejecting this may cause difficulty in deployment and development.

/cc @zhangjinpeng1987 @huachaohuang @siddontang

**Comment by huachaohuang** [comment]
Any context about why we need to do this?

**Comment by AndreMouche** [comment]
Since libc  with lower version haven't implement functions like `setmntent` @MyonKeminta

**Pull request closed without merging**
