### PR TITLE
rc2.2: pick optimize for rocksdb

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
@siddontang @iamxy PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
Need to add in CircleCI?

**Comment by siddontang** [comment]
LGTM

**Comment by BusyJay** [comment]
#1839 should be included too.

**Comment by iamxy** [comment]
LGTM

**Comment by andelf** [comment]
+FIX go compile download url in ci script.

**Pull request merged**
