### PR TITLE
impl Clone for Box<Engine>

### PR DESCRIPTION
**Pull request by codeworm96**
impl Clone for Box\<Engine>, so that we do not need to impl Clone for some structs.
I searched for them, but I am not sure if there are any structs left...

Related to #2876

### CODE REVIEW

**Comment by siddontang** [comment]
Thanks @codeworm96 

PTAL @breeswish

**Comment by MyonKeminta** [comment]
https://doc.rust-lang.org/std/boxed/struct.Box.html#impl-Clone

**Comment by breeswish** [comment]
@hicqu @MyonKeminta `impl Clone for Box<SomeTrait>` is in fact a common style to provide `Clone` for a trait while not making the trait `Sized`. I roughly Googled some examples:

1. https://github.com/hyperium/hyper/blob/0.11.x/src/header/mod.rs#L300
2. https://stackoverflow.com/questions/30353462/how-to-clone-a-struct-storing-a-boxed-trait-object/30353928#30353928
3. https://users.rust-lang.org/t/solved-is-it-possible-to-clone-a-boxed-trait-object/1714

Note that real world usages should be much more, because `impl Clone for Box<..>` is not visible in the documentation of the library itself.

**Comment by breeswish** [comment]
@MyonKeminta Yes, but it is `where T: Clone`, while [`trait Clone: Sized`](https://doc.rust-lang.org/core/clone/trait.Clone.html). There is a lot of effort if we make `Engine: Sized` now.

**Comment by breeswish** [comment]
LGTM

**Comment by siddontang** [comment]
PTAL @Hoverbear

**Comment by hicqu** [comment]
Should we change `Engine::clone` to `Engine::clone_box` like https://github.com/hyperium/hyper/blob/0.11.x/src/header/mod.rs#L300?

**Comment by codeworm96** [comment]
I think it is a good idea and I will take care of that. It conforms the idiom and avoids the `.as_ref()` workaround. I didn't do that previously because `Engine::clone` is used widely in the code.

**Comment by breeswish** [comment]
@codeworm96 Since we are indeed implementing (yet another) `clone()`, I guess the rest of the code is comfortable with that.

**Pull request merged**
