### PR TITLE
cherry-pick:executor/aggregate: convert int to decimal in sum

### PR DESCRIPTION
**Pull request by AndreMouche**
related PR https://github.com/pingcap/tikv/pull/2694 https://github.com/pingcap/tikv/pull/2744 
 @BusyJay @hicqu PTAL

### CODE REVIEW

**Comment by MyonKeminta** [comment]
cargo fmt

**Comment by hicqu** [comment]
LGTM。

**Comment by BusyJay** [comment]
/run-integration-tests tidb=release-1.0 pd=release-1.0 tidb-test=release-1.0

**Comment by AndreMouche** [comment]
/run-integration-tests tidb=release-1.0 pd=release-1.0 tidb-test=release-1.0

**Comment by BusyJay** [comment]
Please update the title, it's not correct anymore.

**Pull request merged**
