### PR TITLE
travis: remove compilation cache

### PR DESCRIPTION
**Pull request by BusyJay**
OS X build often fails when packaging new caches which is produced during compilation, so remove it to make it easier to finish. Though this will slow down CI check.

@siddontang @disksing PTAL

### CODE REVIEW

**Comment by siddontang** [comment]
CI failed....

**Comment by BusyJay** [comment]
They failed due to compilation takes too long time.

**Comment by siddontang** [comment]
Can we support Mac in CircleCI? @andelf

**Comment by disksing** [comment]
LGTM

**Pull request merged**
