### PR TITLE
tests: relax channel timeout check

### LINKED ISSUE #3298: test_unbounded fails on MacOS constantly
## Bug Report

**What did you do?**

```
EXTRA_CARGO_ARGS="test_unbounded" make dev
```

**What did you see instead?**

```
running 1 test
thread 'util::mpsc::tests::test_unbounded' panicked at 'assertion failed: (i64::from(timer.elapsed().subsec_nanos()) - 100000000).abs() < 1000000', src/util/mpsc.rs:301:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:511
   5: <core::alloc::CollectionAllocErr as core::convert::From<core::alloc::AllocErr>>::from
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:445
   6: tikv::util::mpsc::tests::test_unbounded
             at src/util/mpsc.rs:301
   7: tikv::__test::TESTS::{{closure}}
             at src/util/mpsc.rs:288
   8: core::ops::function::FnOnce::call_once
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
   9: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
             at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:640
  10: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
test util::mpsc::tests::test_unbounded ... FAILED

failures:

failures:
    util::mpsc::tests::test_unbounded

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 492 filtered out
```

### PR DESCRIPTION
**Pull request by BusyJay**
Timeout is not precise on Mac OS. This pr relax it by only checking the lower bound.

Close #3298.

### CODE REVIEW

**Comment by overvenus** [comment]
I'm not familiar with macOS, defer to @breeswish .

**Comment by siddontang** [comment]
PTAL @breeswish

**Comment by breeswish** [comment]
LGTM

**Pull request merged**
