### PR TITLE
set dynamic_level_bytes on by default

### PR DESCRIPTION
**Pull request by zhangjinpeng1987**
We set `dynamic_level_bytes` on by default to limit space amplification in some situations.
`ingest sst` will add the sst to the bottommost level if there is no overlap with existing ssts, level 6 by default. We use `ingest sst` to replicate regions' peers, so the LSM structure may like this:
L0 ssts
L1 ssts
L2 ssts
L3~L5 is empty
L6 ssts(ingested by replicating)
When user delete these datas which contained in ssts at level 6, these delete marks are hard to reach level 6. So the disk space occupied by these ssts is hard to reclaim.
When `dynamic_level_bytes` is on, for an empty DB, RocksDB makes last level the base level, which means merging L0 data into the last level, until it exceeds max_bytes_for_level_base. And then RocksDB makes the second last level to be base level, and so on.
For the above case, if `dynamic_level_bytes` is on, the LSM structure is like this:
L0 ssts
L5 ssts
L6 ssts
The delete marks will be compacted from L0 to L5, from L5 to L6. The relevant space occupied by these keys will be freed.

It is not recommended to change this value on db which is not empty. If you really want to change this value, please use `pd-ctl` to compact the whole db first.
$./bin/tikv-ctl --host={$tikv-ip}:{$tikv-port} compact -c write
$./bin/tikv-ctl --host={$tikv-ip}:{$tikv-port} compact -c default

### CODE REVIEW

**Comment by ngaut** [comment]
Why change the configuration? What's the pros and cons?

**Comment by huachaohuang** [comment]
What happens when a DB with a lot of files turns on `dynamic_level_bytes` and restart?

**Comment by siddontang** [comment]
now we have already backed up the previous configuration, so here maybe we can do:

1. For an empty machine, use dynamic by default
2. If not empty, no configuration, use not by default unless we enable it explicitly in the config file
3. If not empty, have the backup configuration, use the previous one. If we want to change, remove the previous configuration.

**Comment by zhangjinpeng1987** [comment]
@siddontang I think it is too complicated. It's better to make things simple.

**Comment by siddontang** [comment]
how to handle the problem as @huachaohuang said above? We should let the user do it automatcially, not manually.

**Comment by BusyJay** [comment]
Any updates?

**Comment by siddontang** [comment]
#3348 is trying to support it, close now.

**Pull request closed without merging**
